// Generated by `wit-bindgen` 0.52.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod wasi {
  pub mod cli {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod environment {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      /// Get the POSIX-style environment variables.
      ///
      /// Each environment variable is provided as a pair of string variable names
      /// and string value.
      ///
      /// Morally, these are a value import, but until value imports are available
      /// in the component model, this import function should return the same
      /// values each time it is called.
      #[allow(async_fn_in_trait)]
      pub fn get_environment() -> _rt::Vec::<(_rt::String,_rt::String,)>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/environment@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-environment"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base10 = l2;
          let len10 = l3;
          let mut result10 = _rt::Vec::with_capacity(len10);
          for i in 0..len10 {
            let base = base10.add(i * (4*::core::mem::size_of::<*const u8>()));
            let e10 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
              let l7 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l8 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len9 = l8;
              let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

              (_rt::string_lift(bytes6), _rt::string_lift(bytes9))
            };
            result10.push(e10);
          }
          _rt::cabi_dealloc(base10, len10 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result11 = result10;
          result11
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// Get the POSIX-style arguments to the program.
      #[allow(async_fn_in_trait)]
      pub fn get_arguments() -> _rt::Vec::<_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/environment@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-arguments"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base7 = l2;
          let len7 = l3;
          let mut result7 = _rt::Vec::with_capacity(len7);
          for i in 0..len7 {
            let base = base7.add(i * (2*::core::mem::size_of::<*const u8>()));
            let e7 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

              _rt::string_lift(bytes6)
            };
            result7.push(e7);
          }
          _rt::cabi_dealloc(base7, len7 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result8 = result7;
          result8
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      /// Return a path that programs should use as their initial current working
      /// directory, interpreting `.` as shorthand for this.
      #[allow(async_fn_in_trait)]
      pub fn initial_cwd() -> Option<_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/environment@0.2.9")]
          unsafe extern "C" {
            #[link_name = "initial-cwd"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result6 = match l2 {
            0 => None,
            1 => {
              let e = {
                let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len5 = l4;
                let bytes5 = _rt::Vec::from_raw_parts(l3.cast(), len5, len5);

                _rt::string_lift(bytes5)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result6
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod exit {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      #[allow(unused_unsafe, clippy::all)]
      /// Exit the current instance and any linked instances.
      #[allow(async_fn_in_trait)]
      pub fn exit(status: Result<(),()>,) -> (){
        unsafe {
          let result0 = match status {
            Ok(_) => { 0i32 },
            Err(_) => { 1i32 },
          };
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/exit@0.2.9")]
          unsafe extern "C" {
            #[link_name = "exit"]
            fn wit_import1(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: i32, ) { unreachable!() }
          wit_import1(result0);
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod stdin {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      pub type InputStream = super::super::super::wasi::io::streams::InputStream;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn get_stdin() -> InputStream{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/stdin@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-stdin"]
            fn wit_import0() -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
          let ret = wit_import0();
          super::super::super::wasi::io::streams::InputStream::from_handle(ret as u32)
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod stdout {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      pub type OutputStream = super::super::super::wasi::io::streams::OutputStream;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn get_stdout() -> OutputStream{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/stdout@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-stdout"]
            fn wit_import0() -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
          let ret = wit_import0();
          super::super::super::wasi::io::streams::OutputStream::from_handle(ret as u32)
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod stderr {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      pub type OutputStream = super::super::super::wasi::io::streams::OutputStream;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn get_stderr() -> OutputStream{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/stderr@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-stderr"]
            fn wit_import0() -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
          let ret = wit_import0();
          super::super::super::wasi::io::streams::OutputStream::from_handle(ret as u32)
        }
      }

    }

    /// Terminal input.
    ///
    /// In the future, this may include functions for disabling echoing,
    /// disabling input buffering so that keyboard events are sent through
    /// immediately, querying supported features, and so on.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod terminal_input {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// The input side of a terminal.

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct TerminalInput{
        handle: _rt::Resource<TerminalInput>,
      }

      impl TerminalInput{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for TerminalInput{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/terminal-input@0.2.9")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]terminal-input"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      

    }

    /// Terminal output.
    ///
    /// In the future, this may include functions for querying the terminal
    /// size, being notified of terminal size changes, querying supported
    /// features, and so on.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod terminal_output {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      /// The output side of a terminal.

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct TerminalOutput{
        handle: _rt::Resource<TerminalOutput>,
      }

      impl TerminalOutput{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for TerminalOutput{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/terminal-output@0.2.9")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]terminal-output"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      

    }

    /// An interface providing an optional `terminal-input` for stdin as a
    /// link-time authority.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod terminal_stdin {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type TerminalInput = super::super::super::wasi::cli::terminal_input::TerminalInput;
      #[allow(unused_unsafe, clippy::all)]
      /// If stdin is connected to a terminal, return a `terminal-input` handle
      /// allowing further interaction with it.
      #[allow(async_fn_in_trait)]
      pub fn get_terminal_stdin() -> Option<TerminalInput>{
        unsafe {

          #[repr(align(4))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/terminal-stdin@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-terminal-stdin"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result4 = match l2 {
            0 => None,
            1 => {
              let e = {
                let l3 = *ptr0.add(4).cast::<i32>();

                super::super::super::wasi::cli::terminal_input::TerminalInput::from_handle(l3 as u32)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result4
        }
      }

    }

    /// An interface providing an optional `terminal-output` for stdout as a
    /// link-time authority.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod terminal_stdout {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type TerminalOutput = super::super::super::wasi::cli::terminal_output::TerminalOutput;
      #[allow(unused_unsafe, clippy::all)]
      /// If stdout is connected to a terminal, return a `terminal-output` handle
      /// allowing further interaction with it.
      #[allow(async_fn_in_trait)]
      pub fn get_terminal_stdout() -> Option<TerminalOutput>{
        unsafe {

          #[repr(align(4))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/terminal-stdout@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-terminal-stdout"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result4 = match l2 {
            0 => None,
            1 => {
              let e = {
                let l3 = *ptr0.add(4).cast::<i32>();

                super::super::super::wasi::cli::terminal_output::TerminalOutput::from_handle(l3 as u32)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result4
        }
      }

    }

    /// An interface providing an optional `terminal-output` for stderr as a
    /// link-time authority.
    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod terminal_stderr {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type TerminalOutput = super::super::super::wasi::cli::terminal_output::TerminalOutput;
      #[allow(unused_unsafe, clippy::all)]
      /// If stderr is connected to a terminal, return a `terminal-output` handle
      /// allowing further interaction with it.
      #[allow(async_fn_in_trait)]
      pub fn get_terminal_stderr() -> Option<TerminalOutput>{
        unsafe {

          #[repr(align(4))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 8]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 8]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:cli/terminal-stderr@0.2.9")]
          unsafe extern "C" {
            #[link_name = "get-terminal-stderr"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result4 = match l2 {
            0 => None,
            1 => {
              let e = {
                let l3 = *ptr0.add(4).cast::<i32>();

                super::super::super::wasi::cli::terminal_output::TerminalOutput::from_handle(l3 as u32)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result4
        }
      }

    }

  }
  pub mod io {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod error {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Error{
        handle: _rt::Resource<Error>,
      }

      impl Error{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Error{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:io/error@0.2.9")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]error"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      impl Error {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn to_debug_string(&self,) -> _rt::String{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/error@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]error.to-debug-string"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = *ptr0.add(0).cast::<*mut u8>();
            let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len4 = l3;
            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
            let result5 = _rt::string_lift(bytes4);
            result5
          }
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod poll {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Pollable{
        handle: _rt::Resource<Pollable>,
      }

      impl Pollable{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Pollable{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:io/poll@0.2.9")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]pollable"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      impl Pollable {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn ready(&self,) -> bool{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/poll@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]pollable.ready"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32 { unreachable!() }
            let ret = wit_import0((self).handle() as i32);
            _rt::bool_lift(ret as u8)
          }
        }
      }
      impl Pollable {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn block(&self,) -> (){
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/poll@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]pollable.block"]
              fn wit_import0(_: i32, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) { unreachable!() }
            wit_import0((self).handle() as i32);
          }
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn poll(in_: &[&Pollable],) -> _rt::Vec::<u32>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let vec0 = in_;
          let len0 = vec0.len();
          let layout0 = _rt::alloc::Layout::from_size_align(vec0.len() * 4, 4).unwrap();
          let (result0, _cleanup0) = wit_bindgen::rt::Cleanup::new(layout0);for (i, e) in vec0.into_iter().enumerate() {
            let base = result0.add(i * 4);
            {
              *base.add(0).cast::<i32>() = (e).handle() as i32;
            }
          }
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:io/poll@0.2.9")]
          unsafe extern "C" {
            #[link_name = "poll"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(result0, len0, ptr1);
          let l3 = *ptr1.add(0).cast::<*mut u8>();
          let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len5 = l4;
          let result6 = <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l3.cast(), len5, len5));
          result6
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod streams {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type Error = super::super::super::wasi::io::error::Error;
      pub type Pollable = super::super::super::wasi::io::poll::Pollable;
      pub enum StreamError {
        LastOperationFailed(Error),
        Closed,
      }
      impl ::core::fmt::Debug for StreamError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            StreamError::LastOperationFailed(e) => {
              f.debug_tuple("StreamError::LastOperationFailed").field(e).finish()
            }
            StreamError::Closed => {
              f.debug_tuple("StreamError::Closed").finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for StreamError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for StreamError {}

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct InputStream{
        handle: _rt::Resource<InputStream>,
      }

      impl InputStream{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for InputStream{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]input-stream"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct OutputStream{
        handle: _rt::Resource<OutputStream>,
      }

      impl OutputStream{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for OutputStream{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]output-stream"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      impl InputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn read(&self,len: u64,) -> Result<_rt::Vec::<u8>,StreamError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]input-stream.read"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result9 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len5 = l4;

                  <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l3.cast(), len5, len5))
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l6 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v8 = match l6 {
                    0 => {
                      let e8 = {
                        let l7 = *ptr0.add(4+1*::core::mem::size_of::<*const u8>()).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l7 as u32)
                      };
                      StreamError::LastOperationFailed(e8)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v8
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result9
          }
        }
      }
      impl InputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn blocking_read(&self,len: u64,) -> Result<_rt::Vec::<u8>,StreamError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]input-stream.blocking-read"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result9 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l4 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len5 = l4;

                  <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l3.cast(), len5, len5))
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l6 = i32::from(*ptr0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  let v8 = match l6 {
                    0 => {
                      let e8 = {
                        let l7 = *ptr0.add(4+1*::core::mem::size_of::<*const u8>()).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l7 as u32)
                      };
                      StreamError::LastOperationFailed(e8)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v8
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result9
          }
        }
      }
      impl InputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn skip(&self,len: u64,) -> Result<u64,StreamError>{
          unsafe {

            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 16]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]input-stream.skip"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result7 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(8).cast::<i64>();

                  l3 as u64
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr0.add(8).cast::<u8>());
                  let v6 = match l4 {
                    0 => {
                      let e6 = {
                        let l5 = *ptr0.add(12).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l5 as u32)
                      };
                      StreamError::LastOperationFailed(e6)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v6
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }
      impl InputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn blocking_skip(&self,len: u64,) -> Result<u64,StreamError>{
          unsafe {

            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 16]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]input-stream.blocking-skip"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result7 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(8).cast::<i64>();

                  l3 as u64
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr0.add(8).cast::<u8>());
                  let v6 = match l4 {
                    0 => {
                      let e6 = {
                        let l5 = *ptr0.add(12).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l5 as u32)
                      };
                      StreamError::LastOperationFailed(e6)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v6
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }
      impl InputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn subscribe(&self,) -> Pollable{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]input-stream.subscribe"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32 { unreachable!() }
            let ret = wit_import0((self).handle() as i32);
            super::super::super::wasi::io::poll::Pollable::from_handle(ret as u32)
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn check_write(&self,) -> Result<u64,StreamError>{
          unsafe {

            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 16]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.check-write"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result7 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(8).cast::<i64>();

                  l3 as u64
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr0.add(8).cast::<u8>());
                  let v6 = match l4 {
                    0 => {
                      let e6 = {
                        let l5 = *ptr0.add(12).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l5 as u32)
                      };
                      StreamError::LastOperationFailed(e6)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v6
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn write(&self,contents: &[u8],) -> Result<(),StreamError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
            let vec0 = contents;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.write"]
              fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import2((self).handle() as i32, ptr0.cast_mut(), len0, ptr1);
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result7 = match l3 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr1.add(4).cast::<u8>());
                  let v6 = match l4 {
                    0 => {
                      let e6 = {
                        let l5 = *ptr1.add(8).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l5 as u32)
                      };
                      StreamError::LastOperationFailed(e6)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v6
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn blocking_write_and_flush(&self,contents: &[u8],) -> Result<(),StreamError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
            let vec0 = contents;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.blocking-write-and-flush"]
              fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import2(_: i32, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import2((self).handle() as i32, ptr0.cast_mut(), len0, ptr1);
            let l3 = i32::from(*ptr1.add(0).cast::<u8>());
            let result7 = match l3 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr1.add(4).cast::<u8>());
                  let v6 = match l4 {
                    0 => {
                      let e6 = {
                        let l5 = *ptr1.add(8).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l5 as u32)
                      };
                      StreamError::LastOperationFailed(e6)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v6
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn flush(&self,) -> Result<(),StreamError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.flush"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result6 = match l2 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(4).cast::<u8>());
                  let v5 = match l3 {
                    0 => {
                      let e5 = {
                        let l4 = *ptr0.add(8).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l4 as u32)
                      };
                      StreamError::LastOperationFailed(e5)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v5
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn blocking_flush(&self,) -> Result<(),StreamError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.blocking-flush"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result6 = match l2 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(4).cast::<u8>());
                  let v5 = match l3 {
                    0 => {
                      let e5 = {
                        let l4 = *ptr0.add(8).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l4 as u32)
                      };
                      StreamError::LastOperationFailed(e5)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v5
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn subscribe(&self,) -> Pollable{
          unsafe {

            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.subscribe"]
              fn wit_import0(_: i32, ) -> i32;
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import0(_: i32, ) -> i32 { unreachable!() }
            let ret = wit_import0((self).handle() as i32);
            super::super::super::wasi::io::poll::Pollable::from_handle(ret as u32)
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn write_zeroes(&self,len: u64,) -> Result<(),StreamError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.write-zeroes"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result6 = match l2 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(4).cast::<u8>());
                  let v5 = match l3 {
                    0 => {
                      let e5 = {
                        let l4 = *ptr0.add(8).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l4 as u32)
                      };
                      StreamError::LastOperationFailed(e5)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v5
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn blocking_write_zeroes_and_flush(&self,len: u64,) -> Result<(),StreamError>{
          unsafe {

            #[repr(align(4))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.blocking-write-zeroes-and-flush"]
              fn wit_import1(_: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result6 = match l2 {
              0 => {
                let e = ();
                Ok(e)
              }
              1 => {
                let e = {
                  let l3 = i32::from(*ptr0.add(4).cast::<u8>());
                  let v5 = match l3 {
                    0 => {
                      let e5 = {
                        let l4 = *ptr0.add(8).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l4 as u32)
                      };
                      StreamError::LastOperationFailed(e5)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v5
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result6
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn splice(&self,src: &InputStream,len: u64,) -> Result<u64,StreamError>{
          unsafe {

            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 16]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.splice"]
              fn wit_import1(_: i32, _: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, (src).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result7 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(8).cast::<i64>();

                  l3 as u64
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr0.add(8).cast::<u8>());
                  let v6 = match l4 {
                    0 => {
                      let e6 = {
                        let l5 = *ptr0.add(12).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l5 as u32)
                      };
                      StreamError::LastOperationFailed(e6)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v6
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }
      impl OutputStream {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn blocking_splice(&self,src: &InputStream,len: u64,) -> Result<u64,StreamError>{
          unsafe {

            #[repr(align(8))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 16]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 16]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wasi:io/streams@0.2.9")]
            unsafe extern "C" {
              #[link_name = "[method]output-stream.blocking-splice"]
              fn wit_import1(_: i32, _: i32, _: i64, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: i32, _: i64, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, (src).handle() as i32, _rt::as_i64(&len), ptr0);
            let l2 = i32::from(*ptr0.add(0).cast::<u8>());
            let result7 = match l2 {
              0 => {
                let e = {
                  let l3 = *ptr0.add(8).cast::<i64>();

                  l3 as u64
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l4 = i32::from(*ptr0.add(8).cast::<u8>());
                  let v6 = match l4 {
                    0 => {
                      let e6 = {
                        let l5 = *ptr0.add(12).cast::<i32>();

                        super::super::super::wasi::io::error::Error::from_handle(l5 as u32)
                      };
                      StreamError::LastOperationFailed(e6)
                    }
                    n => {
                      debug_assert_eq!(n, 1, "invalid enum discriminant");
                      StreamError::Closed
                    }
                  };

                  v6
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result7
          }
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod wacli {
    pub mod cli {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod types {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type ExitCode = u32;
        #[derive(Clone)]
        pub struct CommandMeta {
          pub name: _rt::String,
          pub summary: _rt::String,
          pub usage: _rt::String,
          pub aliases: _rt::Vec::<_rt::String>,
          pub version: _rt::String,
          pub hidden: bool,
          pub description: _rt::String,
          pub examples: _rt::Vec::<_rt::String>,
        }
        impl ::core::fmt::Debug for CommandMeta {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            f.debug_struct("CommandMeta").field("name", &self.name).field("summary", &self.summary).field("usage", &self.usage).field("aliases", &self.aliases).field("version", &self.version).field("hidden", &self.hidden).field("description", &self.description).field("examples", &self.examples).finish()
          }
        }
        #[derive(Clone)]
        pub enum CommandError {
          UnknownCommand(_rt::String),
          InvalidArgs(_rt::String),
          Failed(_rt::String),
          Io(_rt::String),
        }
        impl ::core::fmt::Debug for CommandError {
          fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
            match self {
              CommandError::UnknownCommand(e) => {
                f.debug_tuple("CommandError::UnknownCommand").field(e).finish()
              }
              CommandError::InvalidArgs(e) => {
                f.debug_tuple("CommandError::InvalidArgs").field(e).finish()
              }
              CommandError::Failed(e) => {
                f.debug_tuple("CommandError::Failed").field(e).finish()
              }
              CommandError::Io(e) => {
                f.debug_tuple("CommandError::Io").field(e).finish()
              }
            }
          }
        }
        pub type CommandResult= Result<ExitCode,CommandError>;
        #[doc(hidden)]

        macro_rules! __export_wacli_cli_types_1_0_0_cabi{
          ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

          };);
        }
        #[doc(hidden)]
        pub(crate) use __export_wacli_cli_types_1_0_0_cabi;

      }


      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod host {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type ExitCode = super::super::super::super::exports::wacli::cli::types::ExitCode;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_args_cabi<T: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T::args()
        };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        let vec3 = result0;
        let len3 = vec3.len();
        let layout3 = _rt::alloc::Layout::from_size_align(vec3.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result3, _cleanup3) = wit_bindgen::rt::Cleanup::new(layout3);if let Some(cleanup) = _cleanup3 { cleanup.forget(); }
        for (i, e) in vec3.into_iter().enumerate() {
          let base = result3.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let vec2 = (e.into_bytes()).into_boxed_slice();
            let ptr2 = vec2.as_ptr().cast::<u8>();
            let len2 = vec2.len();
            ::core::mem::forget(vec2);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
            *base.add(0).cast::<*mut u8>() = ptr2.cast_mut();
          }
        }
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
        *ptr1.add(0).cast::<*mut u8>() = result3;
        ptr1
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_args<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base4 = l0;
        let len4 = l1;
        for i in 0..len4 {
          let base = base4.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let l2 = *base.add(0).cast::<*mut u8>();
            let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l2, l3, 1);
          }
        }
        _rt::cabi_dealloc(base4, len4 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_env_cabi<T: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result0 = {
        T::env()
      };
      let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
      let vec5 = result0;
      let len5 = vec5.len();
      let layout5 = _rt::alloc::Layout::from_size_align(vec5.len() * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
      let (result5, _cleanup5) = wit_bindgen::rt::Cleanup::new(layout5);if let Some(cleanup) = _cleanup5 { cleanup.forget(); }
      for (i, e) in vec5.into_iter().enumerate() {
        let base = result5.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let (t2_0, t2_1, ) = e;
          let vec3 = (t2_0.into_bytes()).into_boxed_slice();
          let ptr3 = vec3.as_ptr().cast::<u8>();
          let len3 = vec3.len();
          ::core::mem::forget(vec3);
          *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
          *base.add(0).cast::<*mut u8>() = ptr3.cast_mut();
          let vec4 = (t2_1.into_bytes()).into_boxed_slice();
          let ptr4 = vec4.as_ptr().cast::<u8>();
          let len4 = vec4.len();
          ::core::mem::forget(vec4);
          *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
          *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
        }
      }
      *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
      *ptr1.add(0).cast::<*mut u8>() = result5;
      ptr1
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_env<T: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = *arg0.add(0).cast::<*mut u8>();
      let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
      let base6 = l0;
      let len6 = l1;
      for i in 0..len6 {
        let base = base6.add(i * (4*::core::mem::size_of::<*const u8>()));
        {
          let l2 = *base.add(0).cast::<*mut u8>();
          let l3 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l2, l3, 1);
          let l4 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
          let l5 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
          _rt::cabi_dealloc(l4, l5, 1);
        }
      }
      _rt::cabi_dealloc(base6, len6 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
    } }
    #[doc(hidden)]
    #[allow(non_snake_case, unused_unsafe)]
    pub unsafe fn _export_stdout_write_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) { unsafe {#[cfg(target_arch="wasm32")]
    _rt::run_ctors_once();{
      let len0 = arg1;
      T::stdout_write(<_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0)))
    };
  } }
  #[doc(hidden)]
  #[allow(non_snake_case, unused_unsafe)]
  pub unsafe fn _export_stderr_write_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) { unsafe {#[cfg(target_arch="wasm32")]
  _rt::run_ctors_once();{
    let len0 = arg1;
    T::stderr_write(<_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(arg0.cast(), len0, len0)))
  };
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_stdout_flush_cabi<T: Guest>() { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();{
  T::stdout_flush()
};
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_stderr_flush_cabi<T: Guest>() { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();{
  T::stderr_flush()
};
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_stdin_read_cabi<T: Guest>(arg0: i32,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::stdin_read(arg0 as u32)
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
let vec2 = <_ as Into<_rt::Vec<_>>>::into(result0).into_boxed_slice();
let ptr2 = vec2.as_ptr().cast::<u8>();
let len2 = vec2.len();
::core::mem::forget(vec2);
*ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len2;
*ptr1.add(0).cast::<*mut u8>() = ptr2.cast_mut();
ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case)]
pub unsafe fn __post_return_stdin_read<T: Guest>(arg0: *mut u8,) { unsafe {
  let l0 = *arg0.add(0).cast::<*mut u8>();
  let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
  let base2 = l0;
  let len2 = l1;
  _rt::cabi_dealloc(base2, len2 * 1, 1);
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_is_tty_stdout_cabi<T: Guest>() -> i32 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::is_tty_stdout()
};
match result0 { true => 1, false => 0 }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_is_tty_stderr_cabi<T: Guest>() -> i32 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::is_tty_stderr()
};
match result0 { true => 1, false => 0 }
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_terminal_size_cabi<T: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();let result0 = {
  T::terminal_size()
};
let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
match result0 {
  Some(e) => {
    *ptr1.add(0).cast::<u8>() = (1i32) as u8;
    let (t2_0, t2_1, ) = e;
    *ptr1.add(4).cast::<i32>() = _rt::as_i32(t2_0);
    *ptr1.add(8).cast::<i32>() = _rt::as_i32(t2_1);
  },
  None => {
    {
      *ptr1.add(0).cast::<u8>() = (0i32) as u8;
    }
  },
};ptr1
} }
#[doc(hidden)]
#[allow(non_snake_case, unused_unsafe)]
pub unsafe fn _export_exit_cabi<T: Guest>(arg0: i32,) { unsafe {#[cfg(target_arch="wasm32")]
_rt::run_ctors_once();{
  T::exit(arg0 as u32)
};
} }
pub trait Guest {
  #[allow(async_fn_in_trait)]
  fn args() -> _rt::Vec::<_rt::String>;
  #[allow(async_fn_in_trait)]
  fn env() -> _rt::Vec::<(_rt::String,_rt::String,)>;
  #[allow(async_fn_in_trait)]
  fn stdout_write(bytes: _rt::Vec::<u8>,) -> ();
  #[allow(async_fn_in_trait)]
  fn stderr_write(bytes: _rt::Vec::<u8>,) -> ();
  #[allow(async_fn_in_trait)]
  fn stdout_flush() -> ();
  #[allow(async_fn_in_trait)]
  fn stderr_flush() -> ();
  #[allow(async_fn_in_trait)]
  fn stdin_read(max_bytes: u32,) -> _rt::Vec::<u8>;
  #[allow(async_fn_in_trait)]
  fn is_tty_stdout() -> bool;
  #[allow(async_fn_in_trait)]
  fn is_tty_stderr() -> bool;
  #[allow(async_fn_in_trait)]
  fn terminal_size() -> Option<(u32,u32,)>;
  #[allow(async_fn_in_trait)]
  fn exit(code: ExitCode,) -> ();
}
#[doc(hidden)]

macro_rules! __export_wacli_cli_host_1_0_0_cabi{
  ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

    #[unsafe(export_name = "wacli:cli/host@1.0.0#args")]
    unsafe extern "C" fn export_args() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_args_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_wacli:cli/host@1.0.0#args")]
    unsafe extern "C" fn _post_return_args(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_args::<$ty>(arg0) }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#env")]
    unsafe extern "C" fn export_env() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_env_cabi::<$ty>() }
    }
    #[unsafe(export_name = "cabi_post_wacli:cli/host@1.0.0#env")]
    unsafe extern "C" fn _post_return_env(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_env::<$ty>(arg0) }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#stdout-write")]
    unsafe extern "C" fn export_stdout_write(arg0: *mut u8,arg1: usize,) {
      unsafe { $($path_to_types)*::_export_stdout_write_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#stderr-write")]
    unsafe extern "C" fn export_stderr_write(arg0: *mut u8,arg1: usize,) {
      unsafe { $($path_to_types)*::_export_stderr_write_cabi::<$ty>(arg0, arg1) }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#stdout-flush")]
    unsafe extern "C" fn export_stdout_flush() {
      unsafe { $($path_to_types)*::_export_stdout_flush_cabi::<$ty>() }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#stderr-flush")]
    unsafe extern "C" fn export_stderr_flush() {
      unsafe { $($path_to_types)*::_export_stderr_flush_cabi::<$ty>() }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#stdin-read")]
    unsafe extern "C" fn export_stdin_read(arg0: i32,) -> *mut u8 {
      unsafe { $($path_to_types)*::_export_stdin_read_cabi::<$ty>(arg0) }
    }
    #[unsafe(export_name = "cabi_post_wacli:cli/host@1.0.0#stdin-read")]
    unsafe extern "C" fn _post_return_stdin_read(arg0: *mut u8,) {
      unsafe { $($path_to_types)*::__post_return_stdin_read::<$ty>(arg0) }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#is-tty-stdout")]
    unsafe extern "C" fn export_is_tty_stdout() -> i32 {
      unsafe { $($path_to_types)*::_export_is_tty_stdout_cabi::<$ty>() }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#is-tty-stderr")]
    unsafe extern "C" fn export_is_tty_stderr() -> i32 {
      unsafe { $($path_to_types)*::_export_is_tty_stderr_cabi::<$ty>() }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#terminal-size")]
    unsafe extern "C" fn export_terminal_size() -> *mut u8 {
      unsafe { $($path_to_types)*::_export_terminal_size_cabi::<$ty>() }
    }
    #[unsafe(export_name = "wacli:cli/host@1.0.0#exit")]
    unsafe extern "C" fn export_exit(arg0: i32,) {
      unsafe { $($path_to_types)*::_export_exit_cabi::<$ty>(arg0) }
    }
  };);
}
#[doc(hidden)]
pub(crate) use __export_wacli_cli_host_1_0_0_cabi;

#[cfg_attr(target_pointer_width="64", repr(align(8)))]
#[cfg_attr(target_pointer_width="32", repr(align(4)))]
struct _RetArea([::core::mem::MaybeUninit::<u8>; 8+1*::core::mem::size_of::<*const u8>()]);
static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 8+1*::core::mem::size_of::<*const u8>()]);

}

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::vec::Vec;
  pub use alloc_crate::string::String;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  

  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  pub use alloc_crate::alloc;

  pub fn as_i64<T: AsI64>(t: T) -> i64 {
    t.as_i64()
  }

  pub trait AsI64 {
    fn as_i64(self) -> i64;
  }

  impl<'a, T: Copy + AsI64> AsI64 for &'a T {
    fn as_i64(self) -> i64 {
      (*self).as_i64()
    }
  }
  
  impl AsI64 for i64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  impl AsI64 for u64 {
    #[inline]
    fn as_i64(self) -> i64 {
      self as i64
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_host_provider_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::wacli::cli::types::__export_wacli_cli_types_1_0_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::wacli::cli::types);
  $($path_to_types_root)*::exports::wacli::cli::host::__export_wacli_cli_host_1_0_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::wacli::cli::host);
  )
}
#[doc(inline)]
pub(crate) use __export_host_provider_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.52.0:wacli:cli@1.0.0:host-provider:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 2745] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xb5\x14\x01A\x02\x01\
A%\x01B\x0a\x01o\x02ss\x01p\0\x01@\0\0\x01\x04\0\x0fget-environment\x01\x02\x01p\
s\x01@\0\0\x03\x04\0\x0dget-arguments\x01\x04\x01ks\x01@\0\0\x05\x04\0\x0binitia\
l-cwd\x01\x06\x03\0\x1awasi:cli/environment@0.2.9\x05\0\x01B\x03\x01j\0\0\x01@\x01\
\x06status\0\x01\0\x04\0\x04exit\x01\x01\x03\0\x13wasi:cli/exit@0.2.9\x05\x01\x01\
B\x04\x04\0\x05error\x03\x01\x01h\0\x01@\x01\x04self\x01\0s\x04\0\x1d[method]err\
or.to-debug-string\x01\x02\x03\0\x13wasi:io/error@0.2.9\x05\x02\x01B\x0a\x04\0\x08\
pollable\x03\x01\x01h\0\x01@\x01\x04self\x01\0\x7f\x04\0\x16[method]pollable.rea\
dy\x01\x02\x01@\x01\x04self\x01\x01\0\x04\0\x16[method]pollable.block\x01\x03\x01\
p\x01\x01py\x01@\x01\x02in\x04\0\x05\x04\0\x04poll\x01\x06\x03\0\x12wasi:io/poll\
@0.2.9\x05\x03\x02\x03\0\x02\x05error\x02\x03\0\x03\x08pollable\x01B(\x02\x03\x02\
\x01\x04\x04\0\x05error\x03\0\0\x02\x03\x02\x01\x05\x04\0\x08pollable\x03\0\x02\x01\
i\x01\x01q\x02\x15last-operation-failed\x01\x04\0\x06closed\0\0\x04\0\x0cstream-\
error\x03\0\x05\x04\0\x0cinput-stream\x03\x01\x04\0\x0doutput-stream\x03\x01\x01\
h\x07\x01p}\x01j\x01\x0a\x01\x06\x01@\x02\x04self\x09\x03lenw\0\x0b\x04\0\x19[me\
thod]input-stream.read\x01\x0c\x04\0\"[method]input-stream.blocking-read\x01\x0c\
\x01j\x01w\x01\x06\x01@\x02\x04self\x09\x03lenw\0\x0d\x04\0\x19[method]input-str\
eam.skip\x01\x0e\x04\0\"[method]input-stream.blocking-skip\x01\x0e\x01i\x03\x01@\
\x01\x04self\x09\0\x0f\x04\0\x1e[method]input-stream.subscribe\x01\x10\x01h\x08\x01\
@\x01\x04self\x11\0\x0d\x04\0![method]output-stream.check-write\x01\x12\x01j\0\x01\
\x06\x01@\x02\x04self\x11\x08contents\x0a\0\x13\x04\0\x1b[method]output-stream.w\
rite\x01\x14\x04\0.[method]output-stream.blocking-write-and-flush\x01\x14\x01@\x01\
\x04self\x11\0\x13\x04\0\x1b[method]output-stream.flush\x01\x15\x04\0$[method]ou\
tput-stream.blocking-flush\x01\x15\x01@\x01\x04self\x11\0\x0f\x04\0\x1f[method]o\
utput-stream.subscribe\x01\x16\x01@\x02\x04self\x11\x03lenw\0\x13\x04\0\"[method\
]output-stream.write-zeroes\x01\x17\x04\05[method]output-stream.blocking-write-z\
eroes-and-flush\x01\x17\x01@\x03\x04self\x11\x03src\x09\x03lenw\0\x0d\x04\0\x1c[\
method]output-stream.splice\x01\x18\x04\0%[method]output-stream.blocking-splice\x01\
\x18\x03\0\x15wasi:io/streams@0.2.9\x05\x06\x02\x03\0\x04\x0cinput-stream\x01B\x05\
\x02\x03\x02\x01\x07\x04\0\x0cinput-stream\x03\0\0\x01i\x01\x01@\0\0\x02\x04\0\x09\
get-stdin\x01\x03\x03\0\x14wasi:cli/stdin@0.2.9\x05\x08\x02\x03\0\x04\x0doutput-\
stream\x01B\x05\x02\x03\x02\x01\x09\x04\0\x0doutput-stream\x03\0\0\x01i\x01\x01@\
\0\0\x02\x04\0\x0aget-stdout\x01\x03\x03\0\x15wasi:cli/stdout@0.2.9\x05\x0a\x01B\
\x05\x02\x03\x02\x01\x09\x04\0\x0doutput-stream\x03\0\0\x01i\x01\x01@\0\0\x02\x04\
\0\x0aget-stderr\x01\x03\x03\0\x15wasi:cli/stderr@0.2.9\x05\x0b\x01B\x01\x04\0\x0e\
terminal-input\x03\x01\x03\0\x1dwasi:cli/terminal-input@0.2.9\x05\x0c\x01B\x01\x04\
\0\x0fterminal-output\x03\x01\x03\0\x1ewasi:cli/terminal-output@0.2.9\x05\x0d\x02\
\x03\0\x08\x0eterminal-input\x01B\x06\x02\x03\x02\x01\x0e\x04\0\x0eterminal-inpu\
t\x03\0\0\x01i\x01\x01k\x02\x01@\0\0\x03\x04\0\x12get-terminal-stdin\x01\x04\x03\
\0\x1dwasi:cli/terminal-stdin@0.2.9\x05\x0f\x02\x03\0\x09\x0fterminal-output\x01\
B\x06\x02\x03\x02\x01\x10\x04\0\x0fterminal-output\x03\0\0\x01i\x01\x01k\x02\x01\
@\0\0\x03\x04\0\x13get-terminal-stdout\x01\x04\x03\0\x1ewasi:cli/terminal-stdout\
@0.2.9\x05\x11\x01B\x06\x02\x03\x02\x01\x10\x04\0\x0fterminal-output\x03\0\0\x01\
i\x01\x01k\x02\x01@\0\0\x03\x04\0\x13get-terminal-stderr\x01\x04\x03\0\x1ewasi:c\
li/terminal-stderr@0.2.9\x05\x12\x01B\x09\x01y\x04\0\x09exit-code\x03\0\0\x01ps\x01\
r\x08\x04names\x07summarys\x05usages\x07aliases\x02\x07versions\x06hidden\x7f\x0b\
descriptions\x08examples\x02\x04\0\x0ccommand-meta\x03\0\x03\x01q\x04\x0funknown\
-command\x01s\0\x0cinvalid-args\x01s\0\x06failed\x01s\0\x02io\x01s\0\x04\0\x0dco\
mmand-error\x03\0\x05\x01j\x01\x01\x01\x06\x04\0\x0ecommand-result\x03\0\x07\x04\
\0\x15wacli:cli/types@1.0.0\x05\x13\x02\x03\0\x0d\x09exit-code\x01B\x1b\x02\x03\x02\
\x01\x14\x04\0\x09exit-code\x03\0\0\x01ps\x01@\0\0\x02\x04\0\x04args\x01\x03\x01\
o\x02ss\x01p\x04\x01@\0\0\x05\x04\0\x03env\x01\x06\x01p}\x01@\x01\x05bytes\x07\x01\
\0\x04\0\x0cstdout-write\x01\x08\x04\0\x0cstderr-write\x01\x08\x01@\0\x01\0\x04\0\
\x0cstdout-flush\x01\x09\x04\0\x0cstderr-flush\x01\x09\x01@\x01\x09max-bytesy\0\x07\
\x04\0\x0astdin-read\x01\x0a\x01@\0\0\x7f\x04\0\x0dis-tty-stdout\x01\x0b\x04\0\x0d\
is-tty-stderr\x01\x0b\x01o\x02yy\x01k\x0c\x01@\0\0\x0d\x04\0\x0dterminal-size\x01\
\x0e\x01@\x01\x04code\x01\x01\0\x04\0\x04exit\x01\x0f\x04\0\x14wacli:cli/host@1.\
0.0\x05\x15\x04\0\x1dwacli:cli/host-provider@1.0.0\x04\0\x0b\x13\x01\0\x0dhost-p\
rovider\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.24\
4.0\x10wit-bindgen-rust\x060.52.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

