package wacli:cli@1.0.0;

interface pipe {
  use types.{pipe-meta, pipe-error};

  meta: func() -> pipe-meta;
  process: func(input: list<u8>, options: list<string>) -> result<list<u8>, pipe-error>;
}

world pipe-plugin {
  export pipe;
}
