// Generated by scripts/gen_plugin_loader_bindings.sh
// Source: wit/cli (world=pipe-runtime-host)
// wasmtime=41.0.2
// DO NOT EDIT BY HAND

#[doc(hidden)]
pub use crate::LoadedPipe as __with_name0;

/// Auto-generated bindings for a pre-instantiated version of a
/// component which implements the world `pipe-runtime-host`.
///
/// This structure is created through [`PipeRuntimeHostPre::new`] which
/// takes a [`InstancePre`](wasmtime::component::InstancePre) that
/// has been created through a [`Linker`](wasmtime::component::Linker).
///
/// For more information see [`PipeRuntimeHost`] as well.
pub struct PipeRuntimeHostPre<T: 'static> {
    instance_pre: wasmtime::component::InstancePre<T>,
    indices: PipeRuntimeHostIndices,
}

impl<T: 'static> Clone for PipeRuntimeHostPre<T> {
    fn clone(&self) -> Self {
        Self {
            instance_pre: self.instance_pre.clone(),
            indices: self.indices.clone(),
        }
    }
}

impl<_T: 'static> PipeRuntimeHostPre<_T> {
    /// Creates a new copy of `PipeRuntimeHostPre` bindings which can then
    /// be used to instantiate into a particular store.
    ///
    /// This method may fail if the component behind `instance_pre`
    /// does not have the required exports.
    pub fn new(instance_pre: wasmtime::component::InstancePre<_T>) -> wasmtime::Result<Self> {
        let indices = PipeRuntimeHostIndices::new(&instance_pre)?;
        Ok(Self {
            instance_pre,
            indices,
        })
    }

    pub fn engine(&self) -> &wasmtime::Engine {
        self.instance_pre.engine()
    }

    pub fn instance_pre(&self) -> &wasmtime::component::InstancePre<_T> {
        &self.instance_pre
    }

    /// Instantiates a new instance of [`PipeRuntimeHost`] within the
    /// `store` provided.
    ///
    /// This function will use `self` as the pre-instantiated
    /// instance to perform instantiation. Afterwards the preloaded
    /// indices in `self` are used to lookup all exports on the
    /// resulting instance.
    pub fn instantiate(
        &self,
        mut store: impl wasmtime::AsContextMut<Data = _T>,
    ) -> wasmtime::Result<PipeRuntimeHost> {
        let mut store = store.as_context_mut();
        let instance = self.instance_pre.instantiate(&mut store)?;
        self.indices.load(&mut store, &instance)
    }
}

impl<_T: Send + 'static> PipeRuntimeHostPre<_T> {
    /// Same as [`Self::instantiate`], except with `async`.
    pub async fn instantiate_async(
        &self,
        mut store: impl wasmtime::AsContextMut<Data = _T>,
    ) -> wasmtime::Result<PipeRuntimeHost> {
        let mut store = store.as_context_mut();
        let instance = self.instance_pre.instantiate_async(&mut store).await?;
        self.indices.load(&mut store, &instance)
    }
}

/// Auto-generated bindings for index of the exports of
/// `pipe-runtime-host`.
///
/// This is an implementation detail of [`PipeRuntimeHostPre`] and can
/// be constructed if needed as well.
///
/// For more information see [`PipeRuntimeHost`] as well.
#[derive(Clone)]
pub struct PipeRuntimeHostIndices {}

/// Auto-generated bindings for an instance a component which
/// implements the world `pipe-runtime-host`.
///
/// This structure can be created through a number of means
/// depending on your requirements and what you have on hand:
///
/// * The most convenient way is to use
///   [`PipeRuntimeHost::instantiate`] which only needs a
///   [`Store`], [`Component`], and [`Linker`].
///
/// * Alternatively you can create a [`PipeRuntimeHostPre`] ahead of
///   time with a [`Component`] to front-load string lookups
///   of exports once instead of per-instantiation. This
///   method then uses [`PipeRuntimeHostPre::instantiate`] to
///   create a [`PipeRuntimeHost`].
///
/// * If you've instantiated the instance yourself already
///   then you can use [`PipeRuntimeHost::new`].
///
/// These methods are all equivalent to one another and move
/// around the tradeoff of what work is performed when.
///
/// [`Store`]: wasmtime::Store
/// [`Component`]: wasmtime::component::Component
/// [`Linker`]: wasmtime::component::Linker
pub struct PipeRuntimeHost {}
const _: () = {
    #[allow(unused_imports)]
    use wasmtime::component::__internal::anyhow;

    impl PipeRuntimeHostIndices {
        /// Creates a new copy of `PipeRuntimeHostIndices` bindings which can then
        /// be used to instantiate into a particular store.
        ///
        /// This method may fail if the component does not have the
        /// required exports.
        pub fn new<_T>(
            _instance_pre: &wasmtime::component::InstancePre<_T>,
        ) -> wasmtime::Result<Self> {
            let _component = _instance_pre.component();
            let _instance_type = _instance_pre.instance_type();

            Ok(PipeRuntimeHostIndices {})
        }

        /// Uses the indices stored in `self` to load an instance
        /// of [`PipeRuntimeHost`] from the instance provided.
        ///
        /// Note that at this time this method will additionally
        /// perform type-checks of all exports.
        pub fn load(
            &self,
            mut store: impl wasmtime::AsContextMut,
            instance: &wasmtime::component::Instance,
        ) -> wasmtime::Result<PipeRuntimeHost> {
            let _ = &mut store;
            let _instance = instance;

            Ok(PipeRuntimeHost {})
        }
    }
    impl PipeRuntimeHost {
        /// Convenience wrapper around [`PipeRuntimeHostPre::new`] and
        /// [`PipeRuntimeHostPre::instantiate`].
        pub fn instantiate<_T>(
            store: impl wasmtime::AsContextMut<Data = _T>,
            component: &wasmtime::component::Component,
            linker: &wasmtime::component::Linker<_T>,
        ) -> wasmtime::Result<PipeRuntimeHost> {
            let pre = linker.instantiate_pre(component)?;
            PipeRuntimeHostPre::new(pre)?.instantiate(store)
        }

        /// Convenience wrapper around [`PipeRuntimeHostIndices::new`] and
        /// [`PipeRuntimeHostIndices::load`].
        pub fn new(
            mut store: impl wasmtime::AsContextMut,
            instance: &wasmtime::component::Instance,
        ) -> wasmtime::Result<PipeRuntimeHost> {
            let indices = PipeRuntimeHostIndices::new(&instance.instance_pre(&store))?;
            indices.load(&mut store, instance)
        }

        /// Convenience wrapper around [`PipeRuntimeHostPre::new`] and
        /// [`PipeRuntimeHostPre::instantiate_async`].
        pub async fn instantiate_async<_T>(
            store: impl wasmtime::AsContextMut<Data = _T>,
            component: &wasmtime::component::Component,
            linker: &wasmtime::component::Linker<_T>,
        ) -> wasmtime::Result<PipeRuntimeHost>
        where
            _T: Send,
        {
            let pre = linker.instantiate_pre(component)?;
            PipeRuntimeHostPre::new(pre)?.instantiate_async(store).await
        }

        pub fn add_to_linker<T, D>(
            linker: &mut wasmtime::component::Linker<T>,

            host_getter: fn(&mut T) -> D::Data<'_>,
        ) -> wasmtime::Result<()>
        where
            D: wacli::cli::types::HostWithStore + wacli::cli::pipe_runtime::HostWithStore,
            for<'a> D::Data<'a>: wacli::cli::types::Host + wacli::cli::pipe_runtime::Host,
            T: 'static,
        {
            wacli::cli::types::add_to_linker::<T, D>(linker, host_getter)?;
            wacli::cli::pipe_runtime::add_to_linker::<T, D>(linker, host_getter)?;
            Ok(())
        }
    }
};
pub mod wacli {
    pub mod cli {

        #[allow(clippy::all)]
        pub mod types {
            #[allow(unused_imports)]
            use wasmtime::component::__internal::{anyhow, Box};

            pub type ExitCode = u32;
            const _: () = {
                assert!(4 == <ExitCode as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <ExitCode as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(record)]
            #[derive(Clone)]
            pub struct CommandMeta {
                #[component(name = "name")]
                pub name: wasmtime::component::__internal::String,
                #[component(name = "summary")]
                pub summary: wasmtime::component::__internal::String,
                #[component(name = "usage")]
                pub usage: wasmtime::component::__internal::String,
                #[component(name = "aliases")]
                pub aliases:
                    wasmtime::component::__internal::Vec<wasmtime::component::__internal::String>,
                #[component(name = "version")]
                pub version: wasmtime::component::__internal::String,
                #[component(name = "hidden")]
                pub hidden: bool,
                #[component(name = "description")]
                pub description: wasmtime::component::__internal::String,
                #[component(name = "examples")]
                pub examples:
                    wasmtime::component::__internal::Vec<wasmtime::component::__internal::String>,
            }
            impl core::fmt::Debug for CommandMeta {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    f.debug_struct("CommandMeta")
                        .field("name", &self.name)
                        .field("summary", &self.summary)
                        .field("usage", &self.usage)
                        .field("aliases", &self.aliases)
                        .field("version", &self.version)
                        .field("hidden", &self.hidden)
                        .field("description", &self.description)
                        .field("examples", &self.examples)
                        .finish()
                }
            }
            const _: () = {
                assert!(60 == <CommandMeta as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <CommandMeta as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(variant)]
            #[derive(Clone)]
            pub enum CommandError {
                #[component(name = "unknown-command")]
                UnknownCommand(wasmtime::component::__internal::String),
                #[component(name = "invalid-args")]
                InvalidArgs(wasmtime::component::__internal::String),
                #[component(name = "failed")]
                Failed(wasmtime::component::__internal::String),
                #[component(name = "io")]
                Io(wasmtime::component::__internal::String),
            }
            impl core::fmt::Debug for CommandError {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    match self {
                        CommandError::UnknownCommand(e) => f
                            .debug_tuple("CommandError::UnknownCommand")
                            .field(e)
                            .finish(),
                        CommandError::InvalidArgs(e) => {
                            f.debug_tuple("CommandError::InvalidArgs").field(e).finish()
                        }
                        CommandError::Failed(e) => {
                            f.debug_tuple("CommandError::Failed").field(e).finish()
                        }
                        CommandError::Io(e) => f.debug_tuple("CommandError::Io").field(e).finish(),
                    }
                }
            }
            const _: () = {
                assert!(12 == <CommandError as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <CommandError as wasmtime::component::ComponentType>::ALIGN32);
            };
            pub type CommandResult = Result<ExitCode, CommandError>;
            const _: () = {
                assert!(16 == <CommandResult as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <CommandResult as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(record)]
            #[derive(Clone)]
            pub struct PipeMeta {
                #[component(name = "name")]
                pub name: wasmtime::component::__internal::String,
                #[component(name = "summary")]
                pub summary: wasmtime::component::__internal::String,
                #[component(name = "input-types")]
                pub input_types:
                    wasmtime::component::__internal::Vec<wasmtime::component::__internal::String>,
                #[component(name = "output-type")]
                pub output_type: wasmtime::component::__internal::String,
                #[component(name = "version")]
                pub version: wasmtime::component::__internal::String,
            }
            impl core::fmt::Debug for PipeMeta {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    f.debug_struct("PipeMeta")
                        .field("name", &self.name)
                        .field("summary", &self.summary)
                        .field("input-types", &self.input_types)
                        .field("output-type", &self.output_type)
                        .field("version", &self.version)
                        .finish()
                }
            }
            const _: () = {
                assert!(40 == <PipeMeta as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeMeta as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(variant)]
            #[derive(Clone)]
            pub enum PipeError {
                #[component(name = "parse-error")]
                ParseError(wasmtime::component::__internal::String),
                #[component(name = "transform-error")]
                TransformError(wasmtime::component::__internal::String),
                #[component(name = "invalid-option")]
                InvalidOption(wasmtime::component::__internal::String),
            }
            impl core::fmt::Debug for PipeError {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    match self {
                        PipeError::ParseError(e) => {
                            f.debug_tuple("PipeError::ParseError").field(e).finish()
                        }
                        PipeError::TransformError(e) => {
                            f.debug_tuple("PipeError::TransformError").field(e).finish()
                        }
                        PipeError::InvalidOption(e) => {
                            f.debug_tuple("PipeError::InvalidOption").field(e).finish()
                        }
                    }
                }
            }
            impl core::fmt::Display for PipeError {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl core::error::Error for PipeError {}
            const _: () = {
                assert!(12 == <PipeError as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeError as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(record)]
            #[derive(Clone)]
            pub struct PipeInfo {
                #[component(name = "name")]
                pub name: wasmtime::component::__internal::String,
                #[component(name = "summary")]
                pub summary: wasmtime::component::__internal::String,
                #[component(name = "path")]
                pub path: wasmtime::component::__internal::String,
            }
            impl core::fmt::Debug for PipeInfo {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    f.debug_struct("PipeInfo")
                        .field("name", &self.name)
                        .field("summary", &self.summary)
                        .field("path", &self.path)
                        .finish()
                }
            }
            const _: () = {
                assert!(24 == <PipeInfo as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeInfo as wasmtime::component::ComponentType>::ALIGN32);
            };
            pub trait HostWithStore: wasmtime::component::HasData {}
            impl<_T: ?Sized> HostWithStore for _T where _T: wasmtime::component::HasData {}
            pub trait Host {}
            impl<_T: Host + ?Sized> Host for &mut _T {}

            pub fn add_to_linker<T, D>(
                linker: &mut wasmtime::component::Linker<T>,

                host_getter: fn(&mut T) -> D::Data<'_>,
            ) -> wasmtime::Result<()>
            where
                D: HostWithStore,
                for<'a> D::Data<'a>: Host,
                T: 'static,
            {
                let mut inst = linker.instance("wacli:cli/types@1.0.0")?;
                Ok(())
            }
        }

        #[allow(clippy::all)]
        pub mod pipe_runtime {
            #[allow(unused_imports)]
            use wasmtime::component::__internal::{anyhow, Box};

            pub type PipeMeta = super::super::super::wacli::cli::types::PipeMeta;
            const _: () = {
                assert!(40 == <PipeMeta as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeMeta as wasmtime::component::ComponentType>::ALIGN32);
            };
            pub type PipeError = super::super::super::wacli::cli::types::PipeError;
            const _: () = {
                assert!(12 == <PipeError as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeError as wasmtime::component::ComponentType>::ALIGN32);
            };
            pub type PipeInfo = super::super::super::wacli::cli::types::PipeInfo;
            const _: () = {
                assert!(24 == <PipeInfo as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeInfo as wasmtime::component::ComponentType>::ALIGN32);
            };
            pub use super::super::super::__with_name0 as Pipe;
            pub trait HostPipeWithStore: wasmtime::component::HasData {}
            impl<_T: ?Sized> HostPipeWithStore for _T where _T: wasmtime::component::HasData {}
            pub trait HostPipe {
                fn meta(&mut self, self_: wasmtime::component::Resource<Pipe>) -> PipeMeta;
                fn process(
                    &mut self,
                    self_: wasmtime::component::Resource<Pipe>,
                    input: wasmtime::component::__internal::Vec<u8>,
                    options: wasmtime::component::__internal::Vec<
                        wasmtime::component::__internal::String,
                    >,
                ) -> Result<wasmtime::component::__internal::Vec<u8>, PipeError>;
                fn drop(
                    &mut self,
                    rep: wasmtime::component::Resource<Pipe>,
                ) -> wasmtime::Result<()>;
            }
            impl<_T: HostPipe + ?Sized> HostPipe for &mut _T {
                fn meta(&mut self, self_: wasmtime::component::Resource<Pipe>) -> PipeMeta {
                    HostPipe::meta(*self, self_)
                }
                fn process(
                    &mut self,
                    self_: wasmtime::component::Resource<Pipe>,
                    input: wasmtime::component::__internal::Vec<u8>,
                    options: wasmtime::component::__internal::Vec<
                        wasmtime::component::__internal::String,
                    >,
                ) -> Result<wasmtime::component::__internal::Vec<u8>, PipeError> {
                    HostPipe::process(*self, self_, input, options)
                }

                fn drop(
                    &mut self,
                    rep: wasmtime::component::Resource<Pipe>,
                ) -> wasmtime::Result<()> {
                    HostPipe::drop(*self, rep)
                }
            }
            pub trait HostWithStore: wasmtime::component::HasData + HostPipeWithStore {}
            impl<_T: ?Sized> HostWithStore for _T where _T: wasmtime::component::HasData + HostPipeWithStore {}
            pub trait Host: HostPipe {
                fn list_pipes(&mut self) -> wasmtime::component::__internal::Vec<PipeInfo>;
                fn load_pipe(
                    &mut self,
                    name: wasmtime::component::__internal::String,
                ) -> Result<
                    wasmtime::component::Resource<Pipe>,
                    wasmtime::component::__internal::String,
                >;
            }
            impl<_T: Host + ?Sized> Host for &mut _T {
                fn list_pipes(&mut self) -> wasmtime::component::__internal::Vec<PipeInfo> {
                    Host::list_pipes(*self)
                }
                fn load_pipe(
                    &mut self,
                    name: wasmtime::component::__internal::String,
                ) -> Result<
                    wasmtime::component::Resource<Pipe>,
                    wasmtime::component::__internal::String,
                > {
                    Host::load_pipe(*self, name)
                }
            }

            pub fn add_to_linker<T, D>(
                linker: &mut wasmtime::component::Linker<T>,

                host_getter: fn(&mut T) -> D::Data<'_>,
            ) -> wasmtime::Result<()>
            where
                D: HostWithStore,
                for<'a> D::Data<'a>: Host,
                T: 'static,
            {
                let mut inst = linker.instance("wacli:cli/pipe-runtime@1.0.0")?;
                inst.resource(
                    "pipe",
                    wasmtime::component::ResourceType::host::<Pipe>(),
                    move |mut store, rep| -> wasmtime::Result<()> {
                        let resource = wasmtime::component::Resource::new_own(rep);
                        HostPipe::drop(&mut host_getter(store.data_mut()), resource)
                    },
                )?;
                inst.func_wrap(
                    "list-pipes",
                    move |mut caller: wasmtime::StoreContextMut<'_, T>, (): ()| {
                        let host = &mut host_getter(caller.data_mut());
                        let r = Host::list_pipes(host);
                        Ok((r,))
                    },
                )?;
                inst.func_wrap(
                    "load-pipe",
                    move |mut caller: wasmtime::StoreContextMut<'_, T>,
                          (arg0,): (wasmtime::component::__internal::String,)| {
                        let host = &mut host_getter(caller.data_mut());
                        let r = Host::load_pipe(host, arg0);
                        Ok((r,))
                    },
                )?;
                inst.func_wrap(
                    "[method]pipe.meta",
                    move |mut caller: wasmtime::StoreContextMut<'_, T>,
                          (arg0,): (wasmtime::component::Resource<Pipe>,)| {
                        let host = &mut host_getter(caller.data_mut());
                        let r = HostPipe::meta(host, arg0);
                        Ok((r,))
                    },
                )?;
                inst.func_wrap(
                    "[method]pipe.process",
                    move |mut caller: wasmtime::StoreContextMut<'_, T>,
                          (arg0, arg1, arg2): (
                        wasmtime::component::Resource<Pipe>,
                        wasmtime::component::__internal::Vec<u8>,
                        wasmtime::component::__internal::Vec<
                            wasmtime::component::__internal::String,
                        >,
                    )| {
                        let host = &mut host_getter(caller.data_mut());
                        let r = HostPipe::process(host, arg0, arg1, arg2);
                        Ok((r,))
                    },
                )?;
                Ok(())
            }
        }
    }
}
