// Generated by scripts/gen_plugin_loader_bindings.sh
// Source: wit/cli (world=pipe-plugin)
// wasmtime=41.0.2
// DO NOT EDIT BY HAND

/// Auto-generated bindings for a pre-instantiated version of a
/// component which implements the world `pipe-plugin`.
///
/// This structure is created through [`PipePluginPre::new`] which
/// takes a [`InstancePre`](wasmtime::component::InstancePre) that
/// has been created through a [`Linker`](wasmtime::component::Linker).
///
/// For more information see [`PipePlugin`] as well.
pub struct PipePluginPre<T: 'static> {
    instance_pre: wasmtime::component::InstancePre<T>,
    indices: PipePluginIndices,
}

impl<T: 'static> Clone for PipePluginPre<T> {
    fn clone(&self) -> Self {
        Self {
            instance_pre: self.instance_pre.clone(),
            indices: self.indices.clone(),
        }
    }
}

impl<_T: 'static> PipePluginPre<_T> {
    /// Creates a new copy of `PipePluginPre` bindings which can then
    /// be used to instantiate into a particular store.
    ///
    /// This method may fail if the component behind `instance_pre`
    /// does not have the required exports.
    pub fn new(instance_pre: wasmtime::component::InstancePre<_T>) -> wasmtime::Result<Self> {
        let indices = PipePluginIndices::new(&instance_pre)?;
        Ok(Self {
            instance_pre,
            indices,
        })
    }

    pub fn engine(&self) -> &wasmtime::Engine {
        self.instance_pre.engine()
    }

    pub fn instance_pre(&self) -> &wasmtime::component::InstancePre<_T> {
        &self.instance_pre
    }

    /// Instantiates a new instance of [`PipePlugin`] within the
    /// `store` provided.
    ///
    /// This function will use `self` as the pre-instantiated
    /// instance to perform instantiation. Afterwards the preloaded
    /// indices in `self` are used to lookup all exports on the
    /// resulting instance.
    pub fn instantiate(
        &self,
        mut store: impl wasmtime::AsContextMut<Data = _T>,
    ) -> wasmtime::Result<PipePlugin> {
        let mut store = store.as_context_mut();
        let instance = self.instance_pre.instantiate(&mut store)?;
        self.indices.load(&mut store, &instance)
    }
}

impl<_T: Send + 'static> PipePluginPre<_T> {
    /// Same as [`Self::instantiate`], except with `async`.
    pub async fn instantiate_async(
        &self,
        mut store: impl wasmtime::AsContextMut<Data = _T>,
    ) -> wasmtime::Result<PipePlugin> {
        let mut store = store.as_context_mut();
        let instance = self.instance_pre.instantiate_async(&mut store).await?;
        self.indices.load(&mut store, &instance)
    }
}

/// Auto-generated bindings for index of the exports of
/// `pipe-plugin`.
///
/// This is an implementation detail of [`PipePluginPre`] and can
/// be constructed if needed as well.
///
/// For more information see [`PipePlugin`] as well.
#[derive(Clone)]
pub struct PipePluginIndices {
    interface0: exports::wacli::cli::pipe::GuestIndices,
}

/// Auto-generated bindings for an instance a component which
/// implements the world `pipe-plugin`.
///
/// This structure can be created through a number of means
/// depending on your requirements and what you have on hand:
///
/// * The most convenient way is to use
///   [`PipePlugin::instantiate`] which only needs a
///   [`Store`], [`Component`], and [`Linker`].
///
/// * Alternatively you can create a [`PipePluginPre`] ahead of
///   time with a [`Component`] to front-load string lookups
///   of exports once instead of per-instantiation. This
///   method then uses [`PipePluginPre::instantiate`] to
///   create a [`PipePlugin`].
///
/// * If you've instantiated the instance yourself already
///   then you can use [`PipePlugin::new`].
///
/// These methods are all equivalent to one another and move
/// around the tradeoff of what work is performed when.
///
/// [`Store`]: wasmtime::Store
/// [`Component`]: wasmtime::component::Component
/// [`Linker`]: wasmtime::component::Linker
pub struct PipePlugin {
    interface0: exports::wacli::cli::pipe::Guest,
}
const _: () = {
    #[allow(unused_imports)]
    use wasmtime::component::__internal::anyhow;

    impl PipePluginIndices {
        /// Creates a new copy of `PipePluginIndices` bindings which can then
        /// be used to instantiate into a particular store.
        ///
        /// This method may fail if the component does not have the
        /// required exports.
        pub fn new<_T>(
            _instance_pre: &wasmtime::component::InstancePre<_T>,
        ) -> wasmtime::Result<Self> {
            let _component = _instance_pre.component();
            let _instance_type = _instance_pre.instance_type();

            let interface0 = exports::wacli::cli::pipe::GuestIndices::new(_instance_pre)?;
            Ok(PipePluginIndices { interface0 })
        }

        /// Uses the indices stored in `self` to load an instance
        /// of [`PipePlugin`] from the instance provided.
        ///
        /// Note that at this time this method will additionally
        /// perform type-checks of all exports.
        pub fn load(
            &self,
            mut store: impl wasmtime::AsContextMut,
            instance: &wasmtime::component::Instance,
        ) -> wasmtime::Result<PipePlugin> {
            let _ = &mut store;
            let _instance = instance;

            let interface0 = self.interface0.load(&mut store, &_instance)?;
            Ok(PipePlugin { interface0 })
        }
    }
    impl PipePlugin {
        /// Convenience wrapper around [`PipePluginPre::new`] and
        /// [`PipePluginPre::instantiate`].
        pub fn instantiate<_T>(
            store: impl wasmtime::AsContextMut<Data = _T>,
            component: &wasmtime::component::Component,
            linker: &wasmtime::component::Linker<_T>,
        ) -> wasmtime::Result<PipePlugin> {
            let pre = linker.instantiate_pre(component)?;
            PipePluginPre::new(pre)?.instantiate(store)
        }

        /// Convenience wrapper around [`PipePluginIndices::new`] and
        /// [`PipePluginIndices::load`].
        pub fn new(
            mut store: impl wasmtime::AsContextMut,
            instance: &wasmtime::component::Instance,
        ) -> wasmtime::Result<PipePlugin> {
            let indices = PipePluginIndices::new(&instance.instance_pre(&store))?;
            indices.load(&mut store, instance)
        }

        /// Convenience wrapper around [`PipePluginPre::new`] and
        /// [`PipePluginPre::instantiate_async`].
        pub async fn instantiate_async<_T>(
            store: impl wasmtime::AsContextMut<Data = _T>,
            component: &wasmtime::component::Component,
            linker: &wasmtime::component::Linker<_T>,
        ) -> wasmtime::Result<PipePlugin>
        where
            _T: Send,
        {
            let pre = linker.instantiate_pre(component)?;
            PipePluginPre::new(pre)?.instantiate_async(store).await
        }

        pub fn add_to_linker<T, D>(
            linker: &mut wasmtime::component::Linker<T>,

            host_getter: fn(&mut T) -> D::Data<'_>,
        ) -> wasmtime::Result<()>
        where
            D: wacli::cli::types::HostWithStore,
            for<'a> D::Data<'a>: wacli::cli::types::Host,
            T: 'static,
        {
            wacli::cli::types::add_to_linker::<T, D>(linker, host_getter)?;
            Ok(())
        }

        pub fn wacli_cli_pipe(&self) -> &exports::wacli::cli::pipe::Guest {
            &self.interface0
        }
    }
};
pub mod wacli {
    pub mod cli {

        #[allow(clippy::all)]
        pub mod types {
            #[allow(unused_imports)]
            use wasmtime::component::__internal::{anyhow, Box};

            pub type ExitCode = u32;
            const _: () = {
                assert!(4 == <ExitCode as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <ExitCode as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(record)]
            #[derive(Clone)]
            pub struct CommandMeta {
                #[component(name = "name")]
                pub name: wasmtime::component::__internal::String,
                #[component(name = "summary")]
                pub summary: wasmtime::component::__internal::String,
                #[component(name = "usage")]
                pub usage: wasmtime::component::__internal::String,
                #[component(name = "aliases")]
                pub aliases:
                    wasmtime::component::__internal::Vec<wasmtime::component::__internal::String>,
                #[component(name = "version")]
                pub version: wasmtime::component::__internal::String,
                #[component(name = "hidden")]
                pub hidden: bool,
                #[component(name = "description")]
                pub description: wasmtime::component::__internal::String,
                #[component(name = "examples")]
                pub examples:
                    wasmtime::component::__internal::Vec<wasmtime::component::__internal::String>,
            }
            impl core::fmt::Debug for CommandMeta {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    f.debug_struct("CommandMeta")
                        .field("name", &self.name)
                        .field("summary", &self.summary)
                        .field("usage", &self.usage)
                        .field("aliases", &self.aliases)
                        .field("version", &self.version)
                        .field("hidden", &self.hidden)
                        .field("description", &self.description)
                        .field("examples", &self.examples)
                        .finish()
                }
            }
            const _: () = {
                assert!(60 == <CommandMeta as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <CommandMeta as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(variant)]
            #[derive(Clone)]
            pub enum CommandError {
                #[component(name = "unknown-command")]
                UnknownCommand(wasmtime::component::__internal::String),
                #[component(name = "invalid-args")]
                InvalidArgs(wasmtime::component::__internal::String),
                #[component(name = "failed")]
                Failed(wasmtime::component::__internal::String),
                #[component(name = "io")]
                Io(wasmtime::component::__internal::String),
            }
            impl core::fmt::Debug for CommandError {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    match self {
                        CommandError::UnknownCommand(e) => f
                            .debug_tuple("CommandError::UnknownCommand")
                            .field(e)
                            .finish(),
                        CommandError::InvalidArgs(e) => {
                            f.debug_tuple("CommandError::InvalidArgs").field(e).finish()
                        }
                        CommandError::Failed(e) => {
                            f.debug_tuple("CommandError::Failed").field(e).finish()
                        }
                        CommandError::Io(e) => f.debug_tuple("CommandError::Io").field(e).finish(),
                    }
                }
            }
            const _: () = {
                assert!(12 == <CommandError as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <CommandError as wasmtime::component::ComponentType>::ALIGN32);
            };
            pub type CommandResult = Result<ExitCode, CommandError>;
            const _: () = {
                assert!(16 == <CommandResult as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <CommandResult as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(record)]
            #[derive(Clone)]
            pub struct PipeMeta {
                #[component(name = "name")]
                pub name: wasmtime::component::__internal::String,
                #[component(name = "summary")]
                pub summary: wasmtime::component::__internal::String,
                #[component(name = "input-types")]
                pub input_types:
                    wasmtime::component::__internal::Vec<wasmtime::component::__internal::String>,
                #[component(name = "output-type")]
                pub output_type: wasmtime::component::__internal::String,
                #[component(name = "version")]
                pub version: wasmtime::component::__internal::String,
            }
            impl core::fmt::Debug for PipeMeta {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    f.debug_struct("PipeMeta")
                        .field("name", &self.name)
                        .field("summary", &self.summary)
                        .field("input-types", &self.input_types)
                        .field("output-type", &self.output_type)
                        .field("version", &self.version)
                        .finish()
                }
            }
            const _: () = {
                assert!(40 == <PipeMeta as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeMeta as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(variant)]
            #[derive(Clone)]
            pub enum PipeError {
                #[component(name = "parse-error")]
                ParseError(wasmtime::component::__internal::String),
                #[component(name = "transform-error")]
                TransformError(wasmtime::component::__internal::String),
                #[component(name = "invalid-option")]
                InvalidOption(wasmtime::component::__internal::String),
            }
            impl core::fmt::Debug for PipeError {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    match self {
                        PipeError::ParseError(e) => {
                            f.debug_tuple("PipeError::ParseError").field(e).finish()
                        }
                        PipeError::TransformError(e) => {
                            f.debug_tuple("PipeError::TransformError").field(e).finish()
                        }
                        PipeError::InvalidOption(e) => {
                            f.debug_tuple("PipeError::InvalidOption").field(e).finish()
                        }
                    }
                }
            }
            impl core::fmt::Display for PipeError {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    write!(f, "{:?}", self)
                }
            }
            impl core::error::Error for PipeError {}
            const _: () = {
                assert!(12 == <PipeError as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeError as wasmtime::component::ComponentType>::ALIGN32);
            };
            #[derive(
                wasmtime::component::ComponentType,
                wasmtime::component::Lift,
                wasmtime::component::Lower,
            )]
            #[component(record)]
            #[derive(Clone)]
            pub struct PipeInfo {
                #[component(name = "name")]
                pub name: wasmtime::component::__internal::String,
                #[component(name = "summary")]
                pub summary: wasmtime::component::__internal::String,
                #[component(name = "path")]
                pub path: wasmtime::component::__internal::String,
            }
            impl core::fmt::Debug for PipeInfo {
                fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
                    f.debug_struct("PipeInfo")
                        .field("name", &self.name)
                        .field("summary", &self.summary)
                        .field("path", &self.path)
                        .finish()
                }
            }
            const _: () = {
                assert!(24 == <PipeInfo as wasmtime::component::ComponentType>::SIZE32);
                assert!(4 == <PipeInfo as wasmtime::component::ComponentType>::ALIGN32);
            };
            pub trait HostWithStore: wasmtime::component::HasData {}
            impl<_T: ?Sized> HostWithStore for _T where _T: wasmtime::component::HasData {}
            pub trait Host {}
            impl<_T: Host + ?Sized> Host for &mut _T {}

            pub fn add_to_linker<T, D>(
                linker: &mut wasmtime::component::Linker<T>,

                host_getter: fn(&mut T) -> D::Data<'_>,
            ) -> wasmtime::Result<()>
            where
                D: HostWithStore,
                for<'a> D::Data<'a>: Host,
                T: 'static,
            {
                let mut inst = linker.instance("wacli:cli/types@1.0.0")?;
                Ok(())
            }
        }
    }
}
pub mod exports {
    pub mod wacli {
        pub mod cli {

            #[allow(clippy::all)]
            pub mod pipe {
                #[allow(unused_imports)]
                use wasmtime::component::__internal::{anyhow, Box};

                pub type PipeMeta = super::super::super::super::wacli::cli::types::PipeMeta;
                const _: () = {
                    assert!(40 == <PipeMeta as wasmtime::component::ComponentType>::SIZE32);
                    assert!(4 == <PipeMeta as wasmtime::component::ComponentType>::ALIGN32);
                };
                pub type PipeError = super::super::super::super::wacli::cli::types::PipeError;
                const _: () = {
                    assert!(12 == <PipeError as wasmtime::component::ComponentType>::SIZE32);
                    assert!(4 == <PipeError as wasmtime::component::ComponentType>::ALIGN32);
                };
                #[derive(Clone)]
                pub struct Guest {
                    meta: wasmtime::component::Func,
                    process: wasmtime::component::Func,
                }
                #[derive(Clone)]
                pub struct GuestIndices {
                    meta: wasmtime::component::ComponentExportIndex,
                    process: wasmtime::component::ComponentExportIndex,
                }
                impl GuestIndices {
                    /// Constructor for [`GuestIndices`] which takes a
                    /// [`Component`](wasmtime::component::Component) as input and can be executed
                    /// before instantiation.
                    ///
                    /// This constructor can be used to front-load string lookups to find exports
                    /// within a component.
                    pub fn new<_T>(
                        _instance_pre: &wasmtime::component::InstancePre<_T>,
                    ) -> wasmtime::Result<GuestIndices> {
                        let instance = _instance_pre
                            .component()
                            .get_export_index(None, "wacli:cli/pipe@1.0.0")
                            .ok_or_else(|| {
                                anyhow::anyhow!("no exported instance named `wacli:cli/pipe@1.0.0`")
                            })?;
                        let mut lookup = move |name| {
                            _instance_pre
                                .component()
                                .get_export_index(Some(&instance), name)
                                .ok_or_else(|| {
                                    anyhow::anyhow!(
                                        "instance export `wacli:cli/pipe@1.0.0` does \
                not have export `{name}`"
                                    )
                                })
                        };
                        let _ = &mut lookup;
                        let meta = lookup("meta")?;
                        let process = lookup("process")?;
                        Ok(GuestIndices { meta, process })
                    }

                    pub fn load(
                        &self,
                        mut store: impl wasmtime::AsContextMut,
                        instance: &wasmtime::component::Instance,
                    ) -> wasmtime::Result<Guest> {
                        let _instance = instance;
                        let _instance_pre = _instance.instance_pre(&store);
                        let _instance_type = _instance_pre.instance_type();
                        let mut store = store.as_context_mut();
                        let _ = &mut store;
                        let meta = *_instance
                            .get_typed_func::<(), (PipeMeta,)>(&mut store, &self.meta)?
                            .func();
                        let process = *_instance.get_typed_func::<(&[u8], &[wasmtime::component::__internal::String], ), (Result<wasmtime::component::__internal::Vec<u8>,PipeError>, )>(&mut store, &self.process)?.func();
                        Ok(Guest { meta, process })
                    }
                }
                impl Guest {
                    pub fn call_meta<S: wasmtime::AsContextMut>(
                        &self,
                        mut store: S,
                    ) -> wasmtime::Result<PipeMeta> {
                        let callee = unsafe {
                            wasmtime::component::TypedFunc::<(), (PipeMeta,)>::new_unchecked(
                                self.meta,
                            )
                        };
                        let (ret0,) = callee.call(store.as_context_mut(), ())?;
                        callee.post_return(store.as_context_mut())?;
                        Ok(ret0)
                    }
                    pub fn call_process<S: wasmtime::AsContextMut>(
                        &self,
                        mut store: S,
                        arg0: &[u8],
                        arg1: &[wasmtime::component::__internal::String],
                    ) -> wasmtime::Result<Result<wasmtime::component::__internal::Vec<u8>, PipeError>>
                    {
                        let callee = unsafe {
                            wasmtime::component::TypedFunc::<
                                (&[u8], &[wasmtime::component::__internal::String]),
                                (Result<wasmtime::component::__internal::Vec<u8>, PipeError>,),
                            >::new_unchecked(self.process)
                        };
                        let (ret0,) = callee.call(store.as_context_mut(), (arg0, arg1))?;
                        callee.post_return(store.as_context_mut())?;
                        Ok(ret0)
                    }
                }
            }
        }
    }
}
