#!/usr/bin/env bash
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

profile="debug"
profile_flag=""
if [[ "${1-}" == "--release" ]]; then
  profile="release"
  profile_flag="--release"
fi

export WASMTIME_DEBUG_BINDGEN=1
cargo check -p plugin-loader --features regen-bindings ${profile_flag}
unset WASMTIME_DEBUG_BINDGEN

build_dir="$root/target/${profile}/build"
pipe_plugin_src="$(ls -t "$build_dir"/wasmtime-internal-component-macro-*/out/pipe-plugin*.rs 2>/dev/null | head -n 1 || true)"
pipe_runtime_src="$(ls -t "$build_dir"/wasmtime-internal-component-macro-*/out/pipe-runtime-host*.rs 2>/dev/null | head -n 1 || true)"

if [[ -z "$pipe_plugin_src" || -z "$pipe_runtime_src" ]]; then
  echo "failed to locate generated bindings under $build_dir" >&2
  echo "try running: WASMTIME_DEBUG_BINDGEN=1 cargo check -p plugin-loader ${profile_flag}" >&2
  exit 1
fi

wasmtime_version="$(awk '
  $1 == "name" && $3 ~ /"wasmtime"/ { in_pkg=1 }
  in_pkg && $1 == "version" { gsub(/"/, "", $3); print $3; exit }
' Cargo.lock 2>/dev/null || true)"
if [[ -z "$wasmtime_version" ]]; then
  wasmtime_version="unknown"
fi

dest_dir="$root/crates/plugin-loader/src/bindings"
mkdir -p "$dest_dir"

write_with_header() {
  local src="$1"
  local world="$2"
  local dest="$3"
  {
    echo "// Generated by scripts/gen_plugin_loader_bindings.sh"
    echo "// Source: wit/cli (world=${world})"
    echo "// wasmtime=${wasmtime_version}"
    echo "// DO NOT EDIT BY HAND"
    echo
    cat "$src"
  } > "$dest"
}

write_with_header "$pipe_plugin_src" "pipe-plugin" "$dest_dir/pipe_plugin.rs"
write_with_header "$pipe_runtime_src" "pipe-runtime-host" "$dest_dir/pipe_runtime_host.rs"

echo "generated from:"
echo "  $pipe_plugin_src"
echo "  $pipe_runtime_src"
echo "updated:"
echo "  $dest_dir/pipe_plugin.rs"
echo "  $dest_dir/pipe_runtime_host.rs"
