// Generated by `wit-bindgen` 0.52.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod wacli {
  pub mod cli {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type ExitCode = u32;
      #[derive(Clone)]
      pub struct CommandMeta {
        pub name: _rt::String,
        pub summary: _rt::String,
        pub usage: _rt::String,
        pub aliases: _rt::Vec::<_rt::String>,
        pub version: _rt::String,
        pub hidden: bool,
        pub description: _rt::String,
        pub examples: _rt::Vec::<_rt::String>,
      }
      impl ::core::fmt::Debug for CommandMeta {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("CommandMeta").field("name", &self.name).field("summary", &self.summary).field("usage", &self.usage).field("aliases", &self.aliases).field("version", &self.version).field("hidden", &self.hidden).field("description", &self.description).field("examples", &self.examples).finish()
        }
      }
      #[derive(Clone)]
      pub enum CommandError {
        UnknownCommand(_rt::String),
        InvalidArgs(_rt::String),
        Failed(_rt::String),
        Io(_rt::String),
      }
      impl ::core::fmt::Debug for CommandError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            CommandError::UnknownCommand(e) => {
              f.debug_tuple("CommandError::UnknownCommand").field(e).finish()
            }
            CommandError::InvalidArgs(e) => {
              f.debug_tuple("CommandError::InvalidArgs").field(e).finish()
            }
            CommandError::Failed(e) => {
              f.debug_tuple("CommandError::Failed").field(e).finish()
            }
            CommandError::Io(e) => {
              f.debug_tuple("CommandError::Io").field(e).finish()
            }
          }
        }
      }
      pub type CommandResult= Result<ExitCode,CommandError>;

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type ExitCode = super::super::super::wacli::cli::types::ExitCode;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn args() -> _rt::Vec::<_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "args"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base7 = l2;
          let len7 = l3;
          let mut result7 = _rt::Vec::with_capacity(len7);
          for i in 0..len7 {
            let base = base7.add(i * (2*::core::mem::size_of::<*const u8>()));
            let e7 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

              _rt::string_lift(bytes6)
            };
            result7.push(e7);
          }
          _rt::cabi_dealloc(base7, len7 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result8 = result7;
          result8
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn env() -> _rt::Vec::<(_rt::String,_rt::String,)>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "env"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base10 = l2;
          let len10 = l3;
          let mut result10 = _rt::Vec::with_capacity(len10);
          for i in 0..len10 {
            let base = base10.add(i * (4*::core::mem::size_of::<*const u8>()));
            let e10 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
              let l7 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l8 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len9 = l8;
              let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

              (_rt::string_lift(bytes6), _rt::string_lift(bytes9))
            };
            result10.push(e10);
          }
          _rt::cabi_dealloc(base10, len10 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result11 = result10;
          result11
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stdout_write(bytes: &[u8],) -> (){
        unsafe {
          let vec0 = bytes;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stdout-write"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stderr_write(bytes: &[u8],) -> (){
        unsafe {
          let vec0 = bytes;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stderr-write"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stdout_flush() -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stdout-flush"]
            fn wit_import0();
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() { unreachable!() }
          wit_import0();
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stderr_flush() -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stderr-flush"]
            fn wit_import0();
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() { unreachable!() }
          wit_import0();
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stdin_read(max_bytes: u32,) -> _rt::Vec::<u8>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stdin-read"]
            fn wit_import1(_: i32, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
          wit_import1(_rt::as_i32(&max_bytes), ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let len4 = l3;
          let result5 = <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l2.cast(), len4, len4));
          result5
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn is_tty_stdout() -> bool{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "is-tty-stdout"]
            fn wit_import0() -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
          let ret = wit_import0();
          _rt::bool_lift(ret as u8)
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn is_tty_stderr() -> bool{
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "is-tty-stderr"]
            fn wit_import0() -> i32;
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() -> i32 { unreachable!() }
          let ret = wit_import0();
          _rt::bool_lift(ret as u8)
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn terminal_size() -> Option<(u32,u32,)>{
        unsafe {

          #[repr(align(4))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 12]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 12]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "terminal-size"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = i32::from(*ptr0.add(0).cast::<u8>());
          let result5 = match l2 {
            0 => None,
            1 => {
              let e = {
                let l3 = *ptr0.add(4).cast::<i32>();
                let l4 = *ptr0.add(8).cast::<i32>();

                (l3 as u32, l4 as u32)
              };
              Some(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result5
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn exit(code: ExitCode,) -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host@1.0.0")]
          unsafe extern "C" {
            #[link_name = "exit"]
            fn wit_import0(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0(_: i32, ) { unreachable!() }
          wit_import0(_rt::as_i32(code));
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod wacli {
    pub mod cli {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod command {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type CommandMeta = super::super::super::super::wacli::cli::types::CommandMeta;
        pub type CommandResult = super::super::super::super::wacli::cli::types::CommandResult;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_meta_cabi<T: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T::meta()
        };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        let super::super::super::super::wacli::cli::types::CommandMeta{ name:name2, summary:summary2, usage:usage2, aliases:aliases2, version:version2, hidden:hidden2, description:description2, examples:examples2, } = result0;
        let vec3 = (name2.into_bytes()).into_boxed_slice();
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        ::core::mem::forget(vec3);
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
        *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
        let vec4 = (summary2.into_bytes()).into_boxed_slice();
        let ptr4 = vec4.as_ptr().cast::<u8>();
        let len4 = vec4.len();
        ::core::mem::forget(vec4);
        *ptr1.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
        *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
        let vec5 = (usage2.into_bytes()).into_boxed_slice();
        let ptr5 = vec5.as_ptr().cast::<u8>();
        let len5 = vec5.len();
        ::core::mem::forget(vec5);
        *ptr1.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
        *ptr1.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
        let vec7 = aliases2;
        let len7 = vec7.len();
        let layout7 = _rt::alloc::Layout::from_size_align(vec7.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result7, _cleanup7) = wit_bindgen::rt::Cleanup::new(layout7);if let Some(cleanup) = _cleanup7 { cleanup.forget(); }
        for (i, e) in vec7.into_iter().enumerate() {
          let base = result7.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let vec6 = (e.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
          }
        }
        *ptr1.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
        *ptr1.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result7;
        let vec8 = (version2.into_bytes()).into_boxed_slice();
        let ptr8 = vec8.as_ptr().cast::<u8>();
        let len8 = vec8.len();
        ::core::mem::forget(vec8);
        *ptr1.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
        *ptr1.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8.cast_mut();
        *ptr1.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>() = (match hidden2 { true => 1, false => 0 }) as u8;
        let vec9 = (description2.into_bytes()).into_boxed_slice();
        let ptr9 = vec9.as_ptr().cast::<u8>();
        let len9 = vec9.len();
        ::core::mem::forget(vec9);
        *ptr1.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
        *ptr1.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr9.cast_mut();
        let vec11 = examples2;
        let len11 = vec11.len();
        let layout11 = _rt::alloc::Layout::from_size_align(vec11.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result11, _cleanup11) = wit_bindgen::rt::Cleanup::new(layout11);if let Some(cleanup) = _cleanup11 { cleanup.forget(); }
        for (i, e) in vec11.into_iter().enumerate() {
          let base = result11.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let vec10 = (e.into_bytes()).into_boxed_slice();
            let ptr10 = vec10.as_ptr().cast::<u8>();
            let len10 = vec10.len();
            ::core::mem::forget(vec10);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len10;
            *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
          }
        }
        *ptr1.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
        *ptr1.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result11;
        ptr1
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_meta<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l0, l1, 1);
        let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l3 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l2, l3, 1);
        let l4 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l5 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l4, l5, 1);
        let l6 = *arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l7 = *arg0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base10 = l6;
        let len10 = l7;
        for i in 0..len10 {
          let base = base10.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let l8 = *base.add(0).cast::<*mut u8>();
            let l9 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l8, l9, 1);
          }
        }
        _rt::cabi_dealloc(base10, len10 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        let l11 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l12 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l11, l12, 1);
        let l13 = *arg0.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l14 = *arg0.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l13, l14, 1);
        let l15 = *arg0.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l16 = *arg0.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base19 = l15;
        let len19 = l16;
        for i in 0..len19 {
          let base = base19.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let l17 = *base.add(0).cast::<*mut u8>();
            let l18 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l17, l18, 1);
          }
        }
        _rt::cabi_dealloc(base19, len19 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_run_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result4 = {
        let base3 = arg0;
        let len3 = arg1;
        let mut result3 = _rt::Vec::with_capacity(len3);
        for i in 0..len3 {
          let base = base3.add(i * (2*::core::mem::size_of::<*const u8>()));
          let e3 = {
            let l0 = *base.add(0).cast::<*mut u8>();
            let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len2 = l1;
            let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);

            _rt::string_lift(bytes2)
          };
          result3.push(e3);
        }
        _rt::cabi_dealloc(base3, len3 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        T::run(result3)
      };
      let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result4 {
        Ok(e) => { {
          *ptr5.add(0).cast::<u8>() = (0i32) as u8;
          *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(e);
        } },
        Err(e) => { {
          *ptr5.add(0).cast::<u8>() = (1i32) as u8;
          use super::super::super::super::wacli::cli::types::CommandError as V10;
          match e {
            V10::UnknownCommand(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
              let vec6 = (e.into_bytes()).into_boxed_slice();
              let ptr6 = vec6.as_ptr().cast::<u8>();
              let len6 = vec6.len();
              ::core::mem::forget(vec6);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
            },
            V10::InvalidArgs(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
              let vec7 = (e.into_bytes()).into_boxed_slice();
              let ptr7 = vec7.as_ptr().cast::<u8>();
              let len7 = vec7.len();
              ::core::mem::forget(vec7);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7.cast_mut();
            },
            V10::Failed(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32) as u8;
              let vec8 = (e.into_bytes()).into_boxed_slice();
              let ptr8 = vec8.as_ptr().cast::<u8>();
              let len8 = vec8.len();
              ::core::mem::forget(vec8);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8.cast_mut();
            },
            V10::Io(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32) as u8;
              let vec9 = (e.into_bytes()).into_boxed_slice();
              let ptr9 = vec9.as_ptr().cast::<u8>();
              let len9 = vec9.len();
              ::core::mem::forget(vec9);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr9.cast_mut();
            },
          }
        } },
      };ptr5
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => (),
        _ => {
          let l1 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l1 {
            0 => {
              let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l3 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l2, l3, 1);
            },
            1 => {
              let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l5 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l4, l5, 1);
            },
            2 => {
              let l6 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l7 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l6, l7, 1);
            },
            _ => {
              let l8 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l9 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l8, l9, 1);
            },
          }
        },
      }
    } }
    pub trait Guest {
      #[allow(async_fn_in_trait)]
      fn meta() -> CommandMeta;
      #[allow(async_fn_in_trait)]
      fn run(argv: _rt::Vec::<_rt::String>,) -> CommandResult;
    }
    #[doc(hidden)]

    macro_rules! __export_wacli_cli_command_1_0_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "wacli:cli/command@1.0.0#meta")]
        unsafe extern "C" fn export_meta() -> *mut u8 {
          unsafe { $($path_to_types)*::_export_meta_cabi::<$ty>() }
        }
        #[unsafe(export_name = "cabi_post_wacli:cli/command@1.0.0#meta")]
        unsafe extern "C" fn _post_return_meta(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_meta::<$ty>(arg0) }
        }
        #[unsafe(export_name = "wacli:cli/command@1.0.0#run")]
        unsafe extern "C" fn export_run(arg0: *mut u8,arg1: usize,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_run_cabi::<$ty>(arg0, arg1) }
        }
        #[unsafe(export_name = "cabi_post_wacli:cli/command@1.0.0#run")]
        unsafe extern "C" fn _post_return_run(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_run::<$ty>(arg0) }
        }
      };);
    }
    #[doc(hidden)]
    pub(crate) use __export_wacli_cli_command_1_0_0_cabi;

    #[cfg_attr(target_pointer_width="64", repr(align(8)))]
    #[cfg_attr(target_pointer_width="32", repr(align(4)))]
    struct _RetArea([::core::mem::MaybeUninit::<u8>; 15*::core::mem::size_of::<*const u8>()]);
    static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 15*::core::mem::size_of::<*const u8>()]);

  }

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::string::String;
  pub use alloc_crate::vec::Vec;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  pub unsafe fn bool_lift(val: u8) -> bool {
    if cfg!(debug_assertions) {
      match val {
        0 => false,
        1 => true,
        _ => panic!("invalid bool discriminant"),
      }
    } else {
      val != 0
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  
  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  pub use alloc_crate::alloc;
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_plugin_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::wacli::cli::command::__export_wacli_cli_command_1_0_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::wacli::cli::command);
  )
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.52.0:wacli:cli@1.0.0:plugin:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 860] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xdf\x05\x01A\x02\x01\
A\x09\x01B\x09\x01y\x04\0\x09exit-code\x03\0\0\x01ps\x01r\x08\x04names\x07summar\
ys\x05usages\x07aliases\x02\x07versions\x06hidden\x7f\x0bdescriptions\x08example\
s\x02\x04\0\x0ccommand-meta\x03\0\x03\x01q\x04\x0funknown-command\x01s\0\x0cinva\
lid-args\x01s\0\x06failed\x01s\0\x02io\x01s\0\x04\0\x0dcommand-error\x03\0\x05\x01\
j\x01\x01\x01\x06\x04\0\x0ecommand-result\x03\0\x07\x03\0\x15wacli:cli/types@1.0\
.0\x05\0\x02\x03\0\0\x09exit-code\x01B\x1b\x02\x03\x02\x01\x01\x04\0\x09exit-cod\
e\x03\0\0\x01ps\x01@\0\0\x02\x04\0\x04args\x01\x03\x01o\x02ss\x01p\x04\x01@\0\0\x05\
\x04\0\x03env\x01\x06\x01p}\x01@\x01\x05bytes\x07\x01\0\x04\0\x0cstdout-write\x01\
\x08\x04\0\x0cstderr-write\x01\x08\x01@\0\x01\0\x04\0\x0cstdout-flush\x01\x09\x04\
\0\x0cstderr-flush\x01\x09\x01@\x01\x09max-bytesy\0\x07\x04\0\x0astdin-read\x01\x0a\
\x01@\0\0\x7f\x04\0\x0dis-tty-stdout\x01\x0b\x04\0\x0dis-tty-stderr\x01\x0b\x01o\
\x02yy\x01k\x0c\x01@\0\0\x0d\x04\0\x0dterminal-size\x01\x0e\x01@\x01\x04code\x01\
\x01\0\x04\0\x04exit\x01\x0f\x03\0\x14wacli:cli/host@1.0.0\x05\x02\x02\x03\0\0\x0c\
command-meta\x02\x03\0\0\x0ecommand-result\x01B\x09\x02\x03\x02\x01\x03\x04\0\x0c\
command-meta\x03\0\0\x02\x03\x02\x01\x04\x04\0\x0ecommand-result\x03\0\x02\x01@\0\
\0\x01\x04\0\x04meta\x01\x04\x01ps\x01@\x01\x04argv\x05\0\x03\x04\0\x03run\x01\x06\
\x04\0\x17wacli:cli/command@1.0.0\x05\x05\x04\0\x16wacli:cli/plugin@1.0.0\x04\0\x0b\
\x0c\x01\0\x06plugin\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-comp\
onent\x070.244.0\x10wit-bindgen-rust\x060.52.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

