// Generated by `wit-bindgen` 0.52.0. DO NOT EDIT!
// Options used:
#[allow(dead_code, clippy::all)]
pub mod wacli {
  pub mod cli {

    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host_env {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn args() -> _rt::Vec::<_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-env@1.0.0")]
          unsafe extern "C" {
            #[link_name = "args"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base7 = l2;
          let len7 = l3;
          let mut result7 = _rt::Vec::with_capacity(len7);
          for i in 0..len7 {
            let base = base7.add(i * (2*::core::mem::size_of::<*const u8>()));
            let e7 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);

              _rt::string_lift(bytes6)
            };
            result7.push(e7);
          }
          _rt::cabi_dealloc(base7, len7 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result8 = result7;
          result8
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn env() -> _rt::Vec::<(_rt::String,_rt::String,)>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-env@1.0.0")]
          unsafe extern "C" {
            #[link_name = "env"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base10 = l2;
          let len10 = l3;
          let mut result10 = _rt::Vec::with_capacity(len10);
          for i in 0..len10 {
            let base = base10.add(i * (4*::core::mem::size_of::<*const u8>()));
            let e10 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
              let l7 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l8 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len9 = l8;
              let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

              (_rt::string_lift(bytes6), _rt::string_lift(bytes9))
            };
            result10.push(e10);
          }
          _rt::cabi_dealloc(base10, len10 * (4*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result11 = result10;
          result11
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host_io {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stdout_write(bytes: &[u8],) -> (){
        unsafe {
          let vec0 = bytes;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-io@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stdout-write"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stderr_write(bytes: &[u8],) -> (){
        unsafe {
          let vec0 = bytes;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-io@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stderr-write"]
            fn wit_import1(_: *mut u8, _: usize, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, _: usize, ) { unreachable!() }
          wit_import1(ptr0.cast_mut(), len0);
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stdout_flush() -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-io@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stdout-flush"]
            fn wit_import0();
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() { unreachable!() }
          wit_import0();
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn stderr_flush() -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-io@1.0.0")]
          unsafe extern "C" {
            #[link_name = "stderr-flush"]
            fn wit_import0();
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0() { unreachable!() }
          wit_import0();
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host_fs {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn read_file(path: &str,) -> Result<_rt::Vec::<u8>,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = path;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-fs@1.0.0")]
          unsafe extern "C" {
            #[link_name = "read-file"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result10 = match l3 {
            0 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len6 = l5;

                <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l4.cast(), len6, len6))
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l7 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l8 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len9 = l8;
                let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);

                _rt::string_lift(bytes9)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result10
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn write_file(path: &str,contents: &[u8],) -> Result<(),_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = path;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let vec1 = contents;
          let ptr1 = vec1.as_ptr().cast::<u8>();
          let len1 = vec1.len();
          let ptr2 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-fs@1.0.0")]
          unsafe extern "C" {
            #[link_name = "write-file"]
            fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import3(_: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import3(ptr0.cast_mut(), len0, ptr1.cast_mut(), len1, ptr2);
          let l4 = i32::from(*ptr2.add(0).cast::<u8>());
          let result8 = match l4 {
            0 => {
              let e = ();
              Ok(e)
            }
            1 => {
              let e = {
                let l5 = *ptr2.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *ptr2.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len7 = l6;
                let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                _rt::string_lift(bytes7)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result8
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn list_dir(path: &str,) -> Result<_rt::Vec::<_rt::String>,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = path;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-fs@1.0.0")]
          unsafe extern "C" {
            #[link_name = "list-dir"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result13 = match l3 {
            0 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l5 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let base9 = l4;
                let len9 = l5;
                let mut result9 = _rt::Vec::with_capacity(len9);
                for i in 0..len9 {
                  let base = base9.add(i * (2*::core::mem::size_of::<*const u8>()));
                  let e9 = {
                    let l6 = *base.add(0).cast::<*mut u8>();
                    let l7 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                    let len8 = l7;
                    let bytes8 = _rt::Vec::from_raw_parts(l6.cast(), len8, len8);

                    _rt::string_lift(bytes8)
                  };
                  result9.push(e9);
                }
                _rt::cabi_dealloc(base9, len9 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());

                result9
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l10 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l11 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len12 = l11;
                let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                _rt::string_lift(bytes12)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result13
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod types {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type ExitCode = u32;
      #[derive(Clone)]
      pub struct CommandMeta {
        pub name: _rt::String,
        pub summary: _rt::String,
        pub usage: _rt::String,
        pub aliases: _rt::Vec::<_rt::String>,
        pub version: _rt::String,
        pub hidden: bool,
        pub description: _rt::String,
        pub examples: _rt::Vec::<_rt::String>,
      }
      impl ::core::fmt::Debug for CommandMeta {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("CommandMeta").field("name", &self.name).field("summary", &self.summary).field("usage", &self.usage).field("aliases", &self.aliases).field("version", &self.version).field("hidden", &self.hidden).field("description", &self.description).field("examples", &self.examples).finish()
        }
      }
      #[derive(Clone)]
      pub enum CommandError {
        UnknownCommand(_rt::String),
        InvalidArgs(_rt::String),
        Failed(_rt::String),
        Io(_rt::String),
      }
      impl ::core::fmt::Debug for CommandError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            CommandError::UnknownCommand(e) => {
              f.debug_tuple("CommandError::UnknownCommand").field(e).finish()
            }
            CommandError::InvalidArgs(e) => {
              f.debug_tuple("CommandError::InvalidArgs").field(e).finish()
            }
            CommandError::Failed(e) => {
              f.debug_tuple("CommandError::Failed").field(e).finish()
            }
            CommandError::Io(e) => {
              f.debug_tuple("CommandError::Io").field(e).finish()
            }
          }
        }
      }
      pub type CommandResult= Result<ExitCode,CommandError>;
      #[derive(Clone)]
      pub struct PipeMeta {
        pub name: _rt::String,
        pub summary: _rt::String,
        pub input_types: _rt::Vec::<_rt::String>,
        pub output_type: _rt::String,
        pub version: _rt::String,
      }
      impl ::core::fmt::Debug for PipeMeta {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("PipeMeta").field("name", &self.name).field("summary", &self.summary).field("input-types", &self.input_types).field("output-type", &self.output_type).field("version", &self.version).finish()
        }
      }
      #[derive(Clone)]
      pub enum PipeError {
        ParseError(_rt::String),
        TransformError(_rt::String),
        InvalidOption(_rt::String),
      }
      impl ::core::fmt::Debug for PipeError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          match self {
            PipeError::ParseError(e) => {
              f.debug_tuple("PipeError::ParseError").field(e).finish()
            }
            PipeError::TransformError(e) => {
              f.debug_tuple("PipeError::TransformError").field(e).finish()
            }
            PipeError::InvalidOption(e) => {
              f.debug_tuple("PipeError::InvalidOption").field(e).finish()
            }
          }
        }
      }
      impl ::core::fmt::Display for PipeError {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          write!(f, "{:?}", self)
        }
      }

      impl ::core::error::Error for PipeError {}
      #[derive(Clone)]
      pub struct PipeInfo {
        pub name: _rt::String,
        pub summary: _rt::String,
        pub path: _rt::String,
      }
      impl ::core::fmt::Debug for PipeInfo {
        fn fmt(&self, f: &mut ::core::fmt::Formatter<'_>) -> ::core::fmt::Result {
          f.debug_struct("PipeInfo").field("name", &self.name).field("summary", &self.summary).field("path", &self.path).finish()
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host_process {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type ExitCode = super::super::super::wacli::cli::types::ExitCode;
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn exit(code: ExitCode,) -> (){
        unsafe {

          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-process@1.0.0")]
          unsafe extern "C" {
            #[link_name = "exit"]
            fn wit_import0(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import0(_: i32, ) { unreachable!() }
          wit_import0(_rt::as_i32(code));
        }
      }

    }


    #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
    pub mod host_pipes {
      #[used]
      #[doc(hidden)]
      static __FORCE_SECTION_REF: fn() =
      super::super::super::__link_custom_section_describing_imports;
      
      use super::super::super::_rt;
      pub type PipeMeta = super::super::super::wacli::cli::types::PipeMeta;
      pub type PipeError = super::super::super::wacli::cli::types::PipeError;
      pub type PipeInfo = super::super::super::wacli::cli::types::PipeInfo;

      #[derive(Debug)]
      #[repr(transparent)]
      pub struct Pipe{
        handle: _rt::Resource<Pipe>,
      }

      impl Pipe{
        #[doc(hidden)]
        pub unsafe fn from_handle(handle: u32) -> Self {
          Self {
            handle: unsafe { _rt::Resource::from_handle(handle) },
          }
        }

        #[doc(hidden)]
        pub fn take_handle(&self) -> u32 {
          _rt::Resource::take_handle(&self.handle)
        }

        #[doc(hidden)]
        pub fn handle(&self) -> u32 {
          _rt::Resource::handle(&self.handle)
        }
      }
      

      unsafe impl _rt::WasmResource for Pipe{
        #[inline]
        unsafe fn drop(_handle: u32) {
          
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-pipes@1.0.0")]
          unsafe extern "C" {
            #[link_name = "[resource-drop]pipe"]
            fn drop(_: i32, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn drop(_: i32, ) { unreachable!() }
          
          unsafe { drop(_handle as i32); }
        }
      }
      
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn list_pipes() -> _rt::Vec::<PipeInfo>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 2*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 2*::core::mem::size_of::<*const u8>()]);
          let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-pipes@1.0.0")]
          unsafe extern "C" {
            #[link_name = "list-pipes"]
            fn wit_import1(_: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import1(_: *mut u8, ) { unreachable!() }
          wit_import1(ptr0);
          let l2 = *ptr0.add(0).cast::<*mut u8>();
          let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
          let base13 = l2;
          let len13 = l3;
          let mut result13 = _rt::Vec::with_capacity(len13);
          for i in 0..len13 {
            let base = base13.add(i * (6*::core::mem::size_of::<*const u8>()));
            let e13 = {
              let l4 = *base.add(0).cast::<*mut u8>();
              let l5 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len6 = l5;
              let bytes6 = _rt::Vec::from_raw_parts(l4.cast(), len6, len6);
              let l7 = *base.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l8 = *base.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len9 = l8;
              let bytes9 = _rt::Vec::from_raw_parts(l7.cast(), len9, len9);
              let l10 = *base.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l11 = *base.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
              let len12 = l11;
              let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

              super::super::super::wacli::cli::types::PipeInfo{
                name: _rt::string_lift(bytes6),
                summary: _rt::string_lift(bytes9),
                path: _rt::string_lift(bytes12),
              }
            };
            result13.push(e13);
          }
          _rt::cabi_dealloc(base13, len13 * (6*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
          let result14 = result13;
          result14
        }
      }
      #[allow(unused_unsafe, clippy::all)]
      #[allow(async_fn_in_trait)]
      pub fn load_pipe(name: &str,) -> Result<Pipe,_rt::String>{
        unsafe {

          #[cfg_attr(target_pointer_width="64", repr(align(8)))]
          #[cfg_attr(target_pointer_width="32", repr(align(4)))]
          struct RetArea([::core::mem::MaybeUninit::<u8>; 3*::core::mem::size_of::<*const u8>()]);
          let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 3*::core::mem::size_of::<*const u8>()]);
          let vec0 = name;
          let ptr0 = vec0.as_ptr().cast::<u8>();
          let len0 = vec0.len();
          let ptr1 = ret_area.0.as_mut_ptr().cast::<u8>();
          #[cfg(target_arch = "wasm32")]
          #[link(wasm_import_module = "wacli:cli/host-pipes@1.0.0")]
          unsafe extern "C" {
            #[link_name = "load-pipe"]
            fn wit_import2(_: *mut u8, _: usize, _: *mut u8, );
          }

          #[cfg(not(target_arch = "wasm32"))]
          unsafe extern "C" fn wit_import2(_: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
          wit_import2(ptr0.cast_mut(), len0, ptr1);
          let l3 = i32::from(*ptr1.add(0).cast::<u8>());
          let result8 = match l3 {
            0 => {
              let e = {
                let l4 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<i32>();

                Pipe::from_handle(l4 as u32)
              };
              Ok(e)
            }
            1 => {
              let e = {
                let l5 = *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                let l6 = *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len7 = l6;
                let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);

                _rt::string_lift(bytes7)
              };
              Err(e)
            }
            _ => _rt::invalid_enum_discriminant(),
          };
          result8
        }
      }
      impl Pipe {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn meta(&self,) -> PipeMeta{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 10*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 10*::core::mem::size_of::<*const u8>()]);
            let ptr0 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wacli:cli/host-pipes@1.0.0")]
            unsafe extern "C" {
              #[link_name = "[method]pipe.meta"]
              fn wit_import1(_: i32, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import1(_: i32, _: *mut u8, ) { unreachable!() }
            wit_import1((self).handle() as i32, ptr0);
            let l2 = *ptr0.add(0).cast::<*mut u8>();
            let l3 = *ptr0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len4 = l3;
            let bytes4 = _rt::Vec::from_raw_parts(l2.cast(), len4, len4);
            let l5 = *ptr0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l6 = *ptr0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len7 = l6;
            let bytes7 = _rt::Vec::from_raw_parts(l5.cast(), len7, len7);
            let l8 = *ptr0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l9 = *ptr0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let base13 = l8;
            let len13 = l9;
            let mut result13 = _rt::Vec::with_capacity(len13);
            for i in 0..len13 {
              let base = base13.add(i * (2*::core::mem::size_of::<*const u8>()));
              let e13 = {
                let l10 = *base.add(0).cast::<*mut u8>();
                let l11 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
                let len12 = l11;
                let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                _rt::string_lift(bytes12)
              };
              result13.push(e13);
            }
            _rt::cabi_dealloc(base13, len13 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
            let l14 = *ptr0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l15 = *ptr0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len16 = l15;
            let bytes16 = _rt::Vec::from_raw_parts(l14.cast(), len16, len16);
            let l17 = *ptr0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
            let l18 = *ptr0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len19 = l18;
            let bytes19 = _rt::Vec::from_raw_parts(l17.cast(), len19, len19);
            let result20 = super::super::super::wacli::cli::types::PipeMeta{
              name: _rt::string_lift(bytes4),
              summary: _rt::string_lift(bytes7),
              input_types: result13,
              output_type: _rt::string_lift(bytes16),
              version: _rt::string_lift(bytes19),
            };
            result20
          }
        }
      }
      impl Pipe {
        #[allow(unused_unsafe, clippy::all)]
        #[allow(async_fn_in_trait)]
        pub fn process(&self,input: &[u8],options: &[_rt::String],) -> Result<_rt::Vec::<u8>,PipeError>{
          unsafe {

            #[cfg_attr(target_pointer_width="64", repr(align(8)))]
            #[cfg_attr(target_pointer_width="32", repr(align(4)))]
            struct RetArea([::core::mem::MaybeUninit::<u8>; 4*::core::mem::size_of::<*const u8>()]);
            let mut ret_area = RetArea([::core::mem::MaybeUninit::uninit(); 4*::core::mem::size_of::<*const u8>()]);
            let vec0 = input;
            let ptr0 = vec0.as_ptr().cast::<u8>();
            let len0 = vec0.len();
            let vec2 = options;
            let len2 = vec2.len();
            let layout2 = _rt::alloc::Layout::from_size_align(vec2.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
            let (result2, _cleanup2) = wit_bindgen::rt::Cleanup::new(layout2);for (i, e) in vec2.into_iter().enumerate() {
              let base = result2.add(i * (2*::core::mem::size_of::<*const u8>()));
              {
                let vec1 = e;
                let ptr1 = vec1.as_ptr().cast::<u8>();
                let len1 = vec1.len();
                *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len1;
                *base.add(0).cast::<*mut u8>() = ptr1.cast_mut();
              }
            }
            let ptr3 = ret_area.0.as_mut_ptr().cast::<u8>();
            #[cfg(target_arch = "wasm32")]
            #[link(wasm_import_module = "wacli:cli/host-pipes@1.0.0")]
            unsafe extern "C" {
              #[link_name = "[method]pipe.process"]
              fn wit_import4(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, );
            }

            #[cfg(not(target_arch = "wasm32"))]
            unsafe extern "C" fn wit_import4(_: i32, _: *mut u8, _: usize, _: *mut u8, _: usize, _: *mut u8, ) { unreachable!() }
            wit_import4((self).handle() as i32, ptr0.cast_mut(), len0, result2, len2, ptr3);
            let l5 = i32::from(*ptr3.add(0).cast::<u8>());
            let result20 = match l5 {
              0 => {
                let e = {
                  let l6 = *ptr3.add(::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                  let l7 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<usize>();
                  let len8 = l7;

                  <_ as From<_rt::Vec<_>>>::from(_rt::Vec::from_raw_parts(l6.cast(), len8, len8))
                };
                Ok(e)
              }
              1 => {
                let e = {
                  let l9 = i32::from(*ptr3.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
                  use super::super::super::wacli::cli::types::PipeError as V19;
                  let v19 = match l9 {
                    0 => {
                      let e19 = {
                        let l10 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l11 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len12 = l11;
                        let bytes12 = _rt::Vec::from_raw_parts(l10.cast(), len12, len12);

                        _rt::string_lift(bytes12)
                      };
                      V19::ParseError(e19)
                    }
                    1 => {
                      let e19 = {
                        let l13 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l14 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len15 = l14;
                        let bytes15 = _rt::Vec::from_raw_parts(l13.cast(), len15, len15);

                        _rt::string_lift(bytes15)
                      };
                      V19::TransformError(e19)
                    }
                    n => {
                      debug_assert_eq!(n, 2, "invalid enum discriminant");
                      let e19 = {
                        let l16 = *ptr3.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
                        let l17 = *ptr3.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
                        let len18 = l17;
                        let bytes18 = _rt::Vec::from_raw_parts(l16.cast(), len18, len18);

                        _rt::string_lift(bytes18)
                      };
                      V19::InvalidOption(e19)
                    }
                  };

                  v19
                };
                Err(e)
              }
              _ => _rt::invalid_enum_discriminant(),
            };
            result20
          }
        }
      }

    }

  }
}
#[allow(dead_code, clippy::all)]
pub mod exports {
  pub mod wacli {
    pub mod cli {

      #[allow(dead_code, async_fn_in_trait, unused_imports, clippy::all)]
      pub mod command {
        #[used]
        #[doc(hidden)]
        static __FORCE_SECTION_REF: fn() =
        super::super::super::super::__link_custom_section_describing_imports;
        
        use super::super::super::super::_rt;
        pub type CommandMeta = super::super::super::super::wacli::cli::types::CommandMeta;
        pub type CommandResult = super::super::super::super::wacli::cli::types::CommandResult;
        #[doc(hidden)]
        #[allow(non_snake_case, unused_unsafe)]
        pub unsafe fn _export_meta_cabi<T: Guest>() -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
        _rt::run_ctors_once();let result0 = {
          T::meta()
        };
        let ptr1 = (&raw mut _RET_AREA.0).cast::<u8>();
        let super::super::super::super::wacli::cli::types::CommandMeta{ name:name2, summary:summary2, usage:usage2, aliases:aliases2, version:version2, hidden:hidden2, description:description2, examples:examples2, } = result0;
        let vec3 = (name2.into_bytes()).into_boxed_slice();
        let ptr3 = vec3.as_ptr().cast::<u8>();
        let len3 = vec3.len();
        ::core::mem::forget(vec3);
        *ptr1.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len3;
        *ptr1.add(0).cast::<*mut u8>() = ptr3.cast_mut();
        let vec4 = (summary2.into_bytes()).into_boxed_slice();
        let ptr4 = vec4.as_ptr().cast::<u8>();
        let len4 = vec4.len();
        ::core::mem::forget(vec4);
        *ptr1.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len4;
        *ptr1.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr4.cast_mut();
        let vec5 = (usage2.into_bytes()).into_boxed_slice();
        let ptr5 = vec5.as_ptr().cast::<u8>();
        let len5 = vec5.len();
        ::core::mem::forget(vec5);
        *ptr1.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>() = len5;
        *ptr1.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr5.cast_mut();
        let vec7 = aliases2;
        let len7 = vec7.len();
        let layout7 = _rt::alloc::Layout::from_size_align(vec7.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result7, _cleanup7) = wit_bindgen::rt::Cleanup::new(layout7);if let Some(cleanup) = _cleanup7 { cleanup.forget(); }
        for (i, e) in vec7.into_iter().enumerate() {
          let base = result7.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let vec6 = (e.into_bytes()).into_boxed_slice();
            let ptr6 = vec6.as_ptr().cast::<u8>();
            let len6 = vec6.len();
            ::core::mem::forget(vec6);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
            *base.add(0).cast::<*mut u8>() = ptr6.cast_mut();
          }
        }
        *ptr1.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
        *ptr1.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result7;
        let vec8 = (version2.into_bytes()).into_boxed_slice();
        let ptr8 = vec8.as_ptr().cast::<u8>();
        let len8 = vec8.len();
        ::core::mem::forget(vec8);
        *ptr1.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
        *ptr1.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8.cast_mut();
        *ptr1.add(10*::core::mem::size_of::<*const u8>()).cast::<u8>() = (match hidden2 { true => 1, false => 0 }) as u8;
        let vec9 = (description2.into_bytes()).into_boxed_slice();
        let ptr9 = vec9.as_ptr().cast::<u8>();
        let len9 = vec9.len();
        ::core::mem::forget(vec9);
        *ptr1.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
        *ptr1.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr9.cast_mut();
        let vec11 = examples2;
        let len11 = vec11.len();
        let layout11 = _rt::alloc::Layout::from_size_align(vec11.len() * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>()).unwrap();
        let (result11, _cleanup11) = wit_bindgen::rt::Cleanup::new(layout11);if let Some(cleanup) = _cleanup11 { cleanup.forget(); }
        for (i, e) in vec11.into_iter().enumerate() {
          let base = result11.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let vec10 = (e.into_bytes()).into_boxed_slice();
            let ptr10 = vec10.as_ptr().cast::<u8>();
            let len10 = vec10.len();
            ::core::mem::forget(vec10);
            *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>() = len10;
            *base.add(0).cast::<*mut u8>() = ptr10.cast_mut();
          }
        }
        *ptr1.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>() = len11;
        *ptr1.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = result11;
        ptr1
      } }
      #[doc(hidden)]
      #[allow(non_snake_case)]
      pub unsafe fn __post_return_meta<T: Guest>(arg0: *mut u8,) { unsafe {
        let l0 = *arg0.add(0).cast::<*mut u8>();
        let l1 = *arg0.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l0, l1, 1);
        let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l3 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l2, l3, 1);
        let l4 = *arg0.add(4*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l5 = *arg0.add(5*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l4, l5, 1);
        let l6 = *arg0.add(6*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l7 = *arg0.add(7*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base10 = l6;
        let len10 = l7;
        for i in 0..len10 {
          let base = base10.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let l8 = *base.add(0).cast::<*mut u8>();
            let l9 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l8, l9, 1);
          }
        }
        _rt::cabi_dealloc(base10, len10 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        let l11 = *arg0.add(8*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l12 = *arg0.add(9*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l11, l12, 1);
        let l13 = *arg0.add(11*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l14 = *arg0.add(12*::core::mem::size_of::<*const u8>()).cast::<usize>();
        _rt::cabi_dealloc(l13, l14, 1);
        let l15 = *arg0.add(13*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
        let l16 = *arg0.add(14*::core::mem::size_of::<*const u8>()).cast::<usize>();
        let base19 = l15;
        let len19 = l16;
        for i in 0..len19 {
          let base = base19.add(i * (2*::core::mem::size_of::<*const u8>()));
          {
            let l17 = *base.add(0).cast::<*mut u8>();
            let l18 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            _rt::cabi_dealloc(l17, l18, 1);
          }
        }
        _rt::cabi_dealloc(base19, len19 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
      } }
      #[doc(hidden)]
      #[allow(non_snake_case, unused_unsafe)]
      pub unsafe fn _export_run_cabi<T: Guest>(arg0: *mut u8,arg1: usize,) -> *mut u8 { unsafe {#[cfg(target_arch="wasm32")]
      _rt::run_ctors_once();let result4 = {
        let base3 = arg0;
        let len3 = arg1;
        let mut result3 = _rt::Vec::with_capacity(len3);
        for i in 0..len3 {
          let base = base3.add(i * (2*::core::mem::size_of::<*const u8>()));
          let e3 = {
            let l0 = *base.add(0).cast::<*mut u8>();
            let l1 = *base.add(::core::mem::size_of::<*const u8>()).cast::<usize>();
            let len2 = l1;
            let bytes2 = _rt::Vec::from_raw_parts(l0.cast(), len2, len2);

            _rt::string_lift(bytes2)
          };
          result3.push(e3);
        }
        _rt::cabi_dealloc(base3, len3 * (2*::core::mem::size_of::<*const u8>()), ::core::mem::size_of::<*const u8>());
        T::run(result3)
      };
      let ptr5 = (&raw mut _RET_AREA.0).cast::<u8>();
      match result4 {
        Ok(e) => { {
          *ptr5.add(0).cast::<u8>() = (0i32) as u8;
          *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<i32>() = _rt::as_i32(e);
        } },
        Err(e) => { {
          *ptr5.add(0).cast::<u8>() = (1i32) as u8;
          use super::super::super::super::wacli::cli::types::CommandError as V10;
          match e {
            V10::UnknownCommand(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (0i32) as u8;
              let vec6 = (e.into_bytes()).into_boxed_slice();
              let ptr6 = vec6.as_ptr().cast::<u8>();
              let len6 = vec6.len();
              ::core::mem::forget(vec6);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len6;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr6.cast_mut();
            },
            V10::InvalidArgs(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (1i32) as u8;
              let vec7 = (e.into_bytes()).into_boxed_slice();
              let ptr7 = vec7.as_ptr().cast::<u8>();
              let len7 = vec7.len();
              ::core::mem::forget(vec7);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len7;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr7.cast_mut();
            },
            V10::Failed(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (2i32) as u8;
              let vec8 = (e.into_bytes()).into_boxed_slice();
              let ptr8 = vec8.as_ptr().cast::<u8>();
              let len8 = vec8.len();
              ::core::mem::forget(vec8);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len8;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr8.cast_mut();
            },
            V10::Io(e) => {
              *ptr5.add(::core::mem::size_of::<*const u8>()).cast::<u8>() = (3i32) as u8;
              let vec9 = (e.into_bytes()).into_boxed_slice();
              let ptr9 = vec9.as_ptr().cast::<u8>();
              let len9 = vec9.len();
              ::core::mem::forget(vec9);
              *ptr5.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>() = len9;
              *ptr5.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>() = ptr9.cast_mut();
            },
          }
        } },
      };ptr5
    } }
    #[doc(hidden)]
    #[allow(non_snake_case)]
    pub unsafe fn __post_return_run<T: Guest>(arg0: *mut u8,) { unsafe {
      let l0 = i32::from(*arg0.add(0).cast::<u8>());
      match l0 {
        0 => (),
        _ => {
          let l1 = i32::from(*arg0.add(::core::mem::size_of::<*const u8>()).cast::<u8>());
          match l1 {
            0 => {
              let l2 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l3 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l2, l3, 1);
            },
            1 => {
              let l4 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l5 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l4, l5, 1);
            },
            2 => {
              let l6 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l7 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l6, l7, 1);
            },
            _ => {
              let l8 = *arg0.add(2*::core::mem::size_of::<*const u8>()).cast::<*mut u8>();
              let l9 = *arg0.add(3*::core::mem::size_of::<*const u8>()).cast::<usize>();
              _rt::cabi_dealloc(l8, l9, 1);
            },
          }
        },
      }
    } }
    pub trait Guest {
      #[allow(async_fn_in_trait)]
      fn meta() -> CommandMeta;
      #[allow(async_fn_in_trait)]
      fn run(argv: _rt::Vec::<_rt::String>,) -> CommandResult;
    }
    #[doc(hidden)]

    macro_rules! __export_wacli_cli_command_1_0_0_cabi{
      ($ty:ident with_types_in $($path_to_types:tt)*) => (const _: () = {

        #[unsafe(export_name = "wacli:cli/command@1.0.0#meta")]
        unsafe extern "C" fn export_meta() -> *mut u8 {
          unsafe { $($path_to_types)*::_export_meta_cabi::<$ty>() }
        }
        #[unsafe(export_name = "cabi_post_wacli:cli/command@1.0.0#meta")]
        unsafe extern "C" fn _post_return_meta(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_meta::<$ty>(arg0) }
        }
        #[unsafe(export_name = "wacli:cli/command@1.0.0#run")]
        unsafe extern "C" fn export_run(arg0: *mut u8,arg1: usize,) -> *mut u8 {
          unsafe { $($path_to_types)*::_export_run_cabi::<$ty>(arg0, arg1) }
        }
        #[unsafe(export_name = "cabi_post_wacli:cli/command@1.0.0#run")]
        unsafe extern "C" fn _post_return_run(arg0: *mut u8,) {
          unsafe { $($path_to_types)*::__post_return_run::<$ty>(arg0) }
        }
      };);
    }
    #[doc(hidden)]
    pub(crate) use __export_wacli_cli_command_1_0_0_cabi;

    #[cfg_attr(target_pointer_width="64", repr(align(8)))]
    #[cfg_attr(target_pointer_width="32", repr(align(4)))]
    struct _RetArea([::core::mem::MaybeUninit::<u8>; 15*::core::mem::size_of::<*const u8>()]);
    static mut _RET_AREA: _RetArea = _RetArea([::core::mem::MaybeUninit::uninit(); 15*::core::mem::size_of::<*const u8>()]);

  }

}
}
}
mod _rt {
  #![allow(dead_code, unused_imports, clippy::all)]
  pub use alloc_crate::vec::Vec;
  pub use alloc_crate::string::String;
  pub unsafe fn string_lift(bytes: Vec<u8>) -> String {
    if cfg!(debug_assertions) {
      String::from_utf8(bytes).unwrap()
    } else {
      unsafe { String::from_utf8_unchecked(bytes) }
    }
  }
  pub unsafe fn cabi_dealloc(ptr: *mut u8, size: usize, align: usize) {
    if size == 0 {
      return;
    }
    unsafe {
      let layout = alloc::Layout::from_size_align_unchecked(size, align);
      alloc::dealloc(ptr, layout);
    }
  }
  pub unsafe fn invalid_enum_discriminant<T>() -> T {
    if cfg!(debug_assertions) {
      panic!("invalid enum discriminant")
    } else {
      unsafe { core::hint::unreachable_unchecked() }
    }
  }
  
  pub fn as_i32<T: AsI32>(t: T) -> i32 {
    t.as_i32()
  }

  pub trait AsI32 {
    fn as_i32(self) -> i32;
  }

  impl<'a, T: Copy + AsI32> AsI32 for &'a T {
    fn as_i32(self) -> i32 {
      (*self).as_i32()
    }
  }
  
  impl AsI32 for i32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u32 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u16 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for i8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for u8 {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for char {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  
  impl AsI32 for usize {
    #[inline]
    fn as_i32(self) -> i32 {
      self as i32
    }
  }
  

  use core::fmt;
  use core::marker;
  use core::sync::atomic::{AtomicU32, Ordering::Relaxed};

  /// A type which represents a component model resource, either imported or
  /// exported into this component.
  ///
  /// This is a low-level wrapper which handles the lifetime of the resource
  /// (namely this has a destructor). The `T` provided defines the component model
  /// intrinsics that this wrapper uses.
  ///
  /// One of the chief purposes of this type is to provide `Deref` implementations
  /// to access the underlying data when it is owned.
  ///
  /// This type is primarily used in generated code for exported and imported
  /// resources.
  #[repr(transparent)]
  pub struct Resource<T: WasmResource> {
    // NB: This would ideally be `u32` but it is not. The fact that this has
    // interior mutability is not exposed in the API of this type except for the
    // `take_handle` method which is supposed to in theory be private.
    //
    // This represents, almost all the time, a valid handle value. When it's
    // invalid it's stored as `u32::MAX`.
    handle: AtomicU32,
    _marker: marker::PhantomData<T>,
  }

  /// A trait which all wasm resources implement, namely providing the ability to
  /// drop a resource.
  ///
  /// This generally is implemented by generated code, not user-facing code.
  #[allow(clippy::missing_safety_doc)]
  pub unsafe trait WasmResource {
    /// Invokes the `[resource-drop]...` intrinsic.
    unsafe fn drop(handle: u32);
  }

  impl<T: WasmResource> Resource<T> {
    #[doc(hidden)]
    pub unsafe fn from_handle(handle: u32) -> Self {
      debug_assert!(handle != 0 && handle != u32::MAX);
      Self {
        handle: AtomicU32::new(handle),
        _marker: marker::PhantomData,
      }
    }

    /// Takes ownership of the handle owned by `resource`.
    ///
    /// Note that this ideally would be `into_handle` taking `Resource<T>` by
    /// ownership. The code generator does not enable that in all situations,
    /// unfortunately, so this is provided instead.
    ///
    /// Also note that `take_handle` is in theory only ever called on values
    /// owned by a generated function. For example a generated function might
    /// take `Resource<T>` as an argument but then call `take_handle` on a
    /// reference to that argument. In that sense the dynamic nature of
    /// `take_handle` should only be exposed internally to generated code, not
    /// to user code.
    #[doc(hidden)]
    pub fn take_handle(resource: &Resource<T>) -> u32 {
      resource.handle.swap(u32::MAX, Relaxed)
    }

    #[doc(hidden)]
    pub fn handle(resource: &Resource<T>) -> u32 {
      resource.handle.load(Relaxed)
    }
  }

  impl<T: WasmResource> fmt::Debug for Resource<T> {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
      f.debug_struct("Resource")
      .field("handle", &self.handle)
      .finish()
    }
  }

  impl<T: WasmResource> Drop for Resource<T> {
    fn drop(&mut self) {
      unsafe {
        match self.handle.load(Relaxed) {
          // If this handle was "taken" then don't do anything in the
          // destructor.
          u32::MAX => {}

          // ... but otherwise do actually destroy it with the imported
          // component model intrinsic as defined through `T`.
          other => T::drop(other),
        }
      }
    }
  }
  pub use alloc_crate::alloc;

  #[cfg(target_arch = "wasm32")]
  pub fn run_ctors_once() {
    wit_bindgen::rt::run_ctors_once();
  }
  extern crate alloc as alloc_crate;
}

/// Generates `#[unsafe(no_mangle)]` functions to export the specified type as
/// the root implementation of all generated traits.
///
/// For more information see the documentation of `wit_bindgen::generate!`.
///
/// ```rust
/// # macro_rules! export{ ($($t:tt)*) => (); }
/// # trait Guest {}
/// struct MyType;
///
/// impl Guest for MyType {
///     // ...
/// }
///
/// export!(MyType);
/// ```
#[allow(unused_macros)]
#[doc(hidden)]

macro_rules! __export_plugin_impl {
  ($ty:ident) => (self::export!($ty with_types_in self););
  ($ty:ident with_types_in $($path_to_types_root:tt)*) => (
  $($path_to_types_root)*::exports::wacli::cli::command::__export_wacli_cli_command_1_0_0_cabi!($ty with_types_in $($path_to_types_root)*::exports::wacli::cli::command);
  )
}
#[doc(inline)]
pub(crate) use __export_plugin_impl as export;

#[cfg(target_arch = "wasm32")]
#[unsafe(link_section = "component-type:wit-bindgen:0.52.0:wacli:cli@1.0.0:plugin:encoded world")]
#[doc(hidden)]
#[allow(clippy::octal_escapes)]
pub static __WIT_BINDGEN_COMPONENT_TYPE: [u8; 1449] = *b"\
\0asm\x0d\0\x01\0\0\x19\x16wit-component-encoding\x04\0\x07\xac\x0a\x01A\x02\x01\
A\x14\x01B\x07\x01ps\x01@\0\0\0\x04\0\x04args\x01\x01\x01o\x02ss\x01p\x02\x01@\0\
\0\x03\x04\0\x03env\x01\x04\x03\0\x18wacli:cli/host-env@1.0.0\x05\0\x01B\x07\x01\
p}\x01@\x01\x05bytes\0\x01\0\x04\0\x0cstdout-write\x01\x01\x04\0\x0cstderr-write\
\x01\x01\x01@\0\x01\0\x04\0\x0cstdout-flush\x01\x02\x04\0\x0cstderr-flush\x01\x02\
\x03\0\x17wacli:cli/host-io@1.0.0\x05\x01\x01B\x0b\x01p}\x01j\x01\0\x01s\x01@\x01\
\x04paths\0\x01\x04\0\x09read-file\x01\x02\x01j\0\x01s\x01@\x02\x04paths\x08cont\
ents\0\0\x03\x04\0\x0awrite-file\x01\x04\x01ps\x01j\x01\x05\x01s\x01@\x01\x04pat\
hs\0\x06\x04\0\x08list-dir\x01\x07\x03\0\x17wacli:cli/host-fs@1.0.0\x05\x02\x01B\
\x0f\x01y\x04\0\x09exit-code\x03\0\0\x01ps\x01r\x08\x04names\x07summarys\x05usag\
es\x07aliases\x02\x07versions\x06hidden\x7f\x0bdescriptions\x08examples\x02\x04\0\
\x0ccommand-meta\x03\0\x03\x01q\x04\x0funknown-command\x01s\0\x0cinvalid-args\x01\
s\0\x06failed\x01s\0\x02io\x01s\0\x04\0\x0dcommand-error\x03\0\x05\x01j\x01\x01\x01\
\x06\x04\0\x0ecommand-result\x03\0\x07\x01r\x05\x04names\x07summarys\x0binput-ty\
pes\x02\x0boutput-types\x07versions\x04\0\x09pipe-meta\x03\0\x09\x01q\x03\x0bpar\
se-error\x01s\0\x0ftransform-error\x01s\0\x0einvalid-option\x01s\0\x04\0\x0apipe\
-error\x03\0\x0b\x01r\x03\x04names\x07summarys\x04paths\x04\0\x09pipe-info\x03\0\
\x0d\x03\0\x15wacli:cli/types@1.0.0\x05\x03\x02\x03\0\x03\x09exit-code\x01B\x04\x02\
\x03\x02\x01\x04\x04\0\x09exit-code\x03\0\0\x01@\x01\x04code\x01\x01\0\x04\0\x04\
exit\x01\x02\x03\0\x1cwacli:cli/host-process@1.0.0\x05\x05\x02\x03\0\x03\x09pipe\
-meta\x02\x03\0\x03\x0apipe-error\x02\x03\0\x03\x09pipe-info\x01B\x16\x02\x03\x02\
\x01\x06\x04\0\x09pipe-meta\x03\0\0\x02\x03\x02\x01\x07\x04\0\x0apipe-error\x03\0\
\x02\x02\x03\x02\x01\x08\x04\0\x09pipe-info\x03\0\x04\x04\0\x04pipe\x03\x01\x01h\
\x06\x01@\x01\x04self\x07\0\x01\x04\0\x11[method]pipe.meta\x01\x08\x01p}\x01ps\x01\
j\x01\x09\x01\x03\x01@\x03\x04self\x07\x05input\x09\x07options\x0a\0\x0b\x04\0\x14\
[method]pipe.process\x01\x0c\x01p\x05\x01@\0\0\x0d\x04\0\x0alist-pipes\x01\x0e\x01\
i\x06\x01j\x01\x0f\x01s\x01@\x01\x04names\0\x10\x04\0\x09load-pipe\x01\x11\x03\0\
\x1awacli:cli/host-pipes@1.0.0\x05\x09\x02\x03\0\x03\x0ccommand-meta\x02\x03\0\x03\
\x0ecommand-result\x01B\x09\x02\x03\x02\x01\x0a\x04\0\x0ccommand-meta\x03\0\0\x02\
\x03\x02\x01\x0b\x04\0\x0ecommand-result\x03\0\x02\x01@\0\0\x01\x04\0\x04meta\x01\
\x04\x01ps\x01@\x01\x04argv\x05\0\x03\x04\0\x03run\x01\x06\x04\0\x17wacli:cli/co\
mmand@1.0.0\x05\x0c\x04\0\x16wacli:cli/plugin@1.0.0\x04\0\x0b\x0c\x01\0\x06plugi\
n\x03\0\0\0G\x09producers\x01\x0cprocessed-by\x02\x0dwit-component\x070.244.0\x10\
wit-bindgen-rust\x060.52.0";

#[inline(never)]
#[doc(hidden)]
pub fn __link_custom_section_describing_imports() {
  wit_bindgen::rt::maybe_link_cabi_realloc();
}

