package wacli:cli@1.0.0;

interface host {
  use types.{exit-code};

  args: func() -> list<string>;
  env: func() -> list<tuple<string, string>>;

  stdout-write: func(bytes: list<u8>);
  stderr-write: func(bytes: list<u8>);
  stdout-flush: func();
  stderr-flush: func();

  read-file: func(path: string) -> result<list<u8>, string>;
  write-file: func(path: string, contents: list<u8>) -> result<_, string>;
  list-dir: func(path: string) -> result<list<string>, string>;

  exit: func(code: exit-code);
}
