package wacli:cli@2.0.0;

interface host-fs {
  read-file: func(path: string) -> result<list<u8>, string>;
  write-file: func(path: string, contents: list<u8>) -> result<_, string>;
  create-dir: func(path: string) -> result<_, string>;
  list-dir: func(path: string) -> result<list<string>, string>;
}
