package wacli:cli@1.0.0;

interface pipe-runtime {
  use types.{pipe-meta, pipe-error, pipe-info};

  list-pipes: func() -> list<pipe-info>;
  load-pipe: func(name: string) -> result<pipe, string>;

  resource pipe {
    meta: func() -> pipe-meta;
    process: func(input: list<u8>, options: list<string>) -> result<list<u8>, pipe-error>;
  }
}

world pipe-runtime-host {
  import pipe-runtime;
}
