package wacli:cli@1.0.0;

use wasi:cli/environment@0.2.9 as wasi-cli-environment;
use wasi:cli/exit@0.2.9 as wasi-cli-exit;
use wasi:cli/stdout@0.2.9 as wasi-cli-stdout;
use wasi:cli/stderr@0.2.9 as wasi-cli-stderr;
use wasi:filesystem/types@0.2.9 as wasi-filesystem-types;
use wasi:filesystem/preopens@0.2.9 as wasi-filesystem-preopens;

world wasi-cli-capabilities {
  import wasi-cli-environment;
  import wasi-cli-exit;
  import wasi-cli-stdout;
  import wasi-cli-stderr;
  import wasi-filesystem-types;
  import wasi-filesystem-preopens;
}

world host-provider {
  include wasi-cli-capabilities;

  export types;
  export host;
}

world core {
  import host;
  import registry;

  export wasi:cli/run@0.2.9;
}
