package wacli:cli@2.0.0;

world host-provider {
  include wasi-cli-capabilities;
  import pipe-runtime;

  export types;
  export schema;
  export host-env;
  export host-io;
  export host-fs;
  export host-process;
  export host-pipes;
}

world core {
  import host-env;
  import host-io;
  import host-process;
  import registry;
  import registry-schema;

  export wasi:cli/run@0.2.9;
}
